import { Wand2, Shield, Cpu, MessageSquare, Zap, Braces } from 'lucide-react';
import { DocPageLayout, DocSection, DocSubSection, Prose, CodeBlock, CodeComment, CodeLine } from '../primitives';

interface Props { lang: 'vi' | 'en'; }

export function AiServiceSection({ lang }: Props) {
    const t = lang === 'vi';
    return (
        <DocPageLayout
            title={t ? 'Trợ lý AI Thông minh' : 'Intelligent AI Assistant'}
            subtitle={t
                ? 'Tận dụng sức mạnh của Google Gemini để tự động hóa việc viết SQL, chuyển đổi ngôn ngữ tự nhiên thành truy vấn và tối ưu hóa hiệu năng.'
                : 'Harness the power of Google Gemini to automate SQL writing, convert natural language to queries, and optimize performance.'}
        >
            <div className="grid md:grid-cols-2 gap-8 mb-12">
                <div className="p-8 border rounded-3xl bg-gradient-to-br from-violet-500/10 via-background to-background relative overflow-hidden group">
                    <div className="absolute -top-12 -right-12 w-48 h-48 bg-violet-500/20 rounded-full blur-3xl group-hover:bg-violet-500/30 transition-colors" />
                    <Wand2 className="w-12 h-12 text-violet-500 mb-6" />
                    <h3 className="text-xl font-bold mb-3">{t ? 'Text-to-SQL Engine' : 'Text-to-SQL Engine'}</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                        {t
                            ? 'Chuyển đổi yêu cầu từ ngôn ngữ con người thành mã SQL thực thi được. Hệ thống tự động gửi kèm Context (Schema lược đồ) để AI hiểu rõ cấu trúc bảng.'
                            : 'Convert human requirements into executable SQL code. The system automatically attaches Schema Context, allowing the AI to understand table structures.'}
                    </p>
                </div>
                <div className="p-8 border rounded-3xl bg-gradient-to-br from-blue-500/10 via-background to-background relative overflow-hidden group">
                    <div className="absolute -top-12 -right-12 w-48 h-48 bg-blue-500/20 rounded-full blur-3xl group-hover:bg-blue-500/30 transition-colors" />
                    <Cpu className="w-12 h-12 text-blue-500 mb-6" />
                    <h3 className="text-xl font-bold mb-3">{t ? 'SQL Optimizer & Fix' : 'SQL Optimizer & Fix'}</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                        {t
                            ? 'Tự động phát hiện lỗi cú pháp và gợi ý cách sửa lỗi. AI cũng có khả năng phân tích độ phức tạp và gợi ý thêm Index.'
                            : 'Automatically detects syntax errors and suggests fixes. The AI also analyzes statement complexity and suggests adding Indexes.'}
                    </p>
                </div>
            </div>

            <DocSection title={t ? 'Các tính năng cốt lõi' : 'Core Features'}>
                <div className="space-y-6">
                    <DocSubSection title={t ? '1. Sinh mã từ ngôn ngữ tự nhiên (NLP)' : '1. Generative SQL (NLP)'}>
                        <Prose>
                            {t ? 'Chỉ cần gõ yêu cầu như "Lấy danh sách 10 khách hàng mua nhiều nhất", trợ lý AI sẽ trả về khối mã SQL hoàn chỉnh.' : 'Simply type a request like "Get the top 10 customers by purchase volume", and the AI assistant will return a complete SQL block.'}
                        </Prose>
                        <CodeBlock title="AI Generated SQL">
                            <CodeComment>{t ? '-- Query sinh bởi Gemini Pro' : '-- Query generated by Gemini Pro'}</CodeComment>
                            <CodeLine>SELECT c.customer_name, SUM(o.total_amount) AS total_spent</CodeLine>
                            <CodeLine>FROM customers c</CodeLine>
                            <CodeLine>JOIN orders o ON c.id = o.customer_id</CodeLine>
                            <CodeLine>GROUP BY c.customer_name</CodeLine>
                            <CodeLine>ORDER BY total_spent DESC LIMIT 10;</CodeLine>
                        </CodeBlock>
                    </DocSubSection>
                </div>
            </DocSection>

            <DocSection title={t ? 'Quyền riêng tư & An toàn (Privacy First)' : 'Privacy & Safety'}>
                <div className="p-8 rounded-3xl bg-emerald-500/5 border border-emerald-500/10 space-y-6">
                    <div className="flex items-center gap-3 text-emerald-600">
                        <Shield className="w-6 h-6" />
                        <h4 className="font-bold uppercase text-xs tracking-widest">{t ? 'Cam kết bảo vệ dữ liệu' : 'Data Protection Commitment'}</h4>
                    </div>
                    <div className="grid md:grid-cols-2 gap-8">
                        <div className="space-y-2">
                            <h5 className="text-sm font-bold flex items-center gap-2"><Zap className="w-4 h-4 text-emerald-500" /> {t ? 'Không gửi dữ liệu nhạy cảm' : 'Zero Private Data Sent'}</h5>
                            <p className="text-xs text-muted-foreground leading-relaxed">
                                {t ? 'Chúng tôi KHÔNG BAO GIỜ gửi dữ liệu thực tế (rows/records) cho AI. Chỉ có Schema Metadata được gửi đi.' : 'We NEVER send actual data (rows/records) to the AI. Only Schema Metadata is transmitted.'}
                            </p>
                        </div>
                        <div className="space-y-2">
                            <h5 className="text-sm font-bold flex items-center gap-2"><Braces className="w-4 h-4 text-emerald-500" /> {t ? 'Xử lý phía Backend' : 'Backend Processing'}</h5>
                            <p className="text-xs text-muted-foreground leading-relaxed">
                                {t ? 'API Key được lưu an toàn tại file .env phía server, không bao giờ lộ ra phía client.' : 'API Keys are securely stored in the server-side .env file and never exposed to the client.'}
                            </p>
                        </div>
                    </div>
                </div>
            </DocSection>

            <DocSection title={t ? 'Mẹo Prompting' : 'Prompt Engineering Tips'}>
                <div className="space-y-4">
                    {[
                        {
                            t: t ? 'Cung cấp ngữ cảnh rõ ràng' : 'Provide Clear Context',
                            d: t ? 'Thay vì gõ "Lấy doanh thu", hãy gõ "Lấy doanh thu theo từng tháng trong năm 2023".' : 'Instead of typing "Get revenue", try "Get revenue by month for 2023".'
                        },
                        {
                            t: t ? 'Sử dụng Keyword kỹ thuật' : 'Use Technical Keywords',
                            d: t ? 'Chủ động yêu cầu "Sử dụng Window Function" hoặc "Viết bằng CTE".' : 'Explicitly ask to "Use Window Functions" or "Write using CTEs".'
                        }
                    ].map((tip, i) => (
                        <div key={i} className="flex gap-4 p-5 border rounded-2xl bg-muted/20 items-start">
                            <div className="p-2 bg-background border rounded-lg"><MessageSquare className="w-4 h-4 text-primary" /></div>
                            <div className="space-y-1">
                                <h5 className="font-bold text-sm tracking-tight">{tip.t}</h5>
                                <p className="text-xs text-muted-foreground leading-relaxed">{tip.d}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </DocSection>
        </DocPageLayout>
    );
}
