import { normalizeAppLang, type AppLang } from './i18n';

const workspaceText = {
    vi: {
        aiQuery: {
            autoInsertSkipped: 'Kết quả AI quá dài hoặc có thay đổi schema nên chưa được chèn tự động.',
            autoInsertWarning: 'Kết quả AI không được chèn tự động vì có thao tác ghi, đổi cấu trúc hoặc quá dài.',
            generatedSuccess: 'Đã sinh mã SQL thành công!',
            generatedFailure: 'Không thể sinh SQL cho yêu cầu này.',
            requestFailed: 'Gọi AI thất bại.',
            collapsedPrompt: 'Gõ tiếng Việt để sinh SQL, ví dụ: 10 khách hàng mới nhất...',
            expandedPlaceholder: 'Mô tả yêu cầu của bạn bằng tiếng Việt hoặc tiếng Anh...',
            badge: 'AI SQL',
            title: 'AI SQL Generator',
            hotkey: 'CTRL + ENTER để chạy',
            contextOn: 'Ngữ cảnh RAG: bật',
            cancel: 'Đóng',
            generate: 'Sinh SQL',
        },
        noSqlAi: {
            collapsedPromptRedis: 'Gõ yêu cầu để sinh lệnh Redis...',
            collapsedPromptMongo: 'Gõ yêu cầu để sinh MQL, ví dụ: lọc các đơn hàng trên 500k...',
            expandedPlaceholderRedis: 'Mô tả lệnh Redis bạn cần, ví dụ: quét session:*, lấy key user:123...',
            expandedPlaceholderMongo: 'Mô tả yêu cầu truy vấn MongoDB của bạn...',
            capabilityNoteRedis: 'AI có thể gợi ý cả lệnh đọc và ghi Redis. Hãy nói rõ nếu bạn muốn set hoặc xóa key.',
            capabilityNoteReadOnly: 'Kết nối này đang ở chế độ chỉ đọc, nên AI chỉ nên sinh find hoặc aggregate cho collection này.',
            capabilityNoteMutable: 'AI có thể sinh find, aggregate, update và delete. Với lệnh ghi dữ liệu, hãy dùng từ rõ ràng như update, delete hoặc remove để hệ thống hiểu đúng ý bạn.',
            quickScanSessions: 'Quét session',
            quickInspectTtl: 'Xem TTL key',
            quickDeleteOldKey: 'Xóa key cũ',
            quickTopCategories: 'Danh mục nhiều nhất',
            quickLatestOrders: 'Đơn mới nhất',
            quickSamplePipeline: 'Pipeline mẫu',
            quickUpdateStatus: 'Cập nhật trạng thái',
            quickDeleteOldLogs: 'Xóa log cũ',
            safeguardExplanation: 'AI đã sinh lệnh ghi dữ liệu hoặc câu lệnh quá dài nên chưa chèn tự động. Nếu bạn thật sự muốn mutate, hãy ghi rõ update, delete hoặc remove trong prompt rồi kiểm tra lại trước khi chạy.',
            safeguardWarning: 'Lệnh NoSQL chưa được chèn tự động vì có thể ghi dữ liệu hoặc quá dài.',
            generatedSuccess: (commandLabel: string) => `Đã sinh ${commandLabel} thành công!`,
            generatedFailure: (commandLabel: string) => `Không thể sinh ${commandLabel} cho yêu cầu này.`,
            requestFailed: 'Gọi AI thất bại.',
            shortcutTitle: 'Prompt gợi ý',
            shortcutHint: 'Bấm để chèn nhanh',
            defaultCollection: 'Mặc định',
            cancel: 'Đóng',
            badge: 'NoSQL AI',
            runHotkey: 'CTRL + ENTER để chạy',
            redisCommandLabel: 'lệnh Redis',
            mqlCommandLabel: 'MQL',
            redisGeneratorTitle: 'AI Redis Generator',
            mqlGeneratorTitle: 'AI MQL Generator',
        },
        aiAssistant: {
            newConversation: 'Cuộc trò chuyện mới',
            chatHistory: 'Lịch sử chat',
            noDatabaseTitle: 'Chưa kết nối database',
            noDatabaseDescription: 'Bạn cần thiết lập Server và Database hoặc NoSQL ở sidebar để AI có thể viết query chính xác hơn.',
            thinking: 'Đang nghĩ...',
            disclaimer: 'AI có thể trả lời không chính xác, hãy kiểm tra lại trước khi chạy.',
            chatCount: (count: number) => `${count} cuộc trò chuyện`,
        },
        aiChat: {
            sqlFromTab: (title: string) => `SQL từ "${title}"`,
            collectionWithoutSchema: (name: string) => `Collection đang mở: ${name} (chưa chạy phân tích schema)`,
            databaseContext: (connectionName: string, database: string, type: string) =>
                `Database đang kết nối: ${connectionName}, Database: ${database}, Type: ${type}`,
            attachmentOnlyPrompt: '(xem hình hoặc ngữ cảnh đính kèm)',
            aborted: 'Đã dừng bởi người dùng',
            error: (message: string) => `Lỗi: ${message}`,
            noDatabaseMessage: 'Chưa kết nối database. Hãy kết nối trước khi dùng AI.',
            attachedSql: 'SQL đính kèm',
            schemaPrefix: (name: string) => `Schema cho collection "${name}":`,
        },
        erd: {
            storageNotReady: 'Kho workspace ERD chưa sẵn sàng',
            loadFailed: 'Không thể tải danh sách workspace ERD',
            storageDescription: 'Trang ERD vẫn dùng được, nhưng bạn cần sync schema backend để lưu workspace.',
        },
        queryProject: {
            title: 'Thư viện truy vấn',
            description: 'Chọn, ghim và mở lại truy vấn như một IDE gọn nhẹ.',
            openLibrary: 'Mở thư viện',
            pinned: 'Đã ghim',
            pinHint: 'Ghim truy vấn để giữ lại các truy vấn quan trọng.',
            recent: 'Gần đây',
            noHistory: 'Chưa có lịch sử chạy truy vấn.',
            run: 'Chạy',
            folders: 'Thư mục',
            noSavedQueries: 'Bạn chưa có truy vấn đã lưu nào.',
            noFolder: 'Không có thư mục',
            queryCount: (count: number) => `${count} truy vấn`,
            topTags: 'Tag phổ biến',
        },
        savedQueries: {
            title: 'Truy vấn đã lưu',
            description: 'Duyệt, xem trước, mở hoặc quản lý các truy vấn đã lưu.',
            searchPlaceholder: 'Tìm truy vấn...',
            unknownOwner: 'Không rõ người tạo',
            deleted: 'Đã xóa truy vấn đã lưu',
            deleteFailed: 'Không thể xóa truy vấn đã lưu',
            pin: 'Ghim',
            unpin: 'Bỏ ghim',
            history: 'Lịch sử',
            preview: 'Xem trước',
            open: 'Mở',
            selectToPreview: 'Chọn một truy vấn để xem trước',
            historyTitle: 'Lịch sử truy vấn đã lưu',
            noVersions: 'Chưa có phiên bản nào',
            name: 'Tên',
        },
        saveQuery: {
            updateTitle: 'Cập nhật truy vấn đã lưu',
            createTitle: 'Lưu truy vấn',
            description: 'Lưu hoặc cập nhật truy vấn cùng phạm vi chia sẻ và mô tả.',
            displayName: 'Tên hiển thị',
            visibility: 'Quyền hiển thị',
            private: 'Riêng tư',
            workspaceWide: 'Toàn workspace',
            workspaceTeam: 'Workspace / Team',
            chooseWorkspace: 'Chọn workspace',
            folderGroup: 'Thư mục / Nhóm',
            tags: 'Tags (phân tách bằng dấu phẩy)',
            details: 'Mô tả',
            detailsPlaceholder: 'Mô tả ngắn để đồng đội hiểu truy vấn này dùng làm gì.',
            cancel: 'Hủy',
            saving: 'Đang lưu...',
            update: 'Cập nhật',
            save: 'Lưu truy vấn',
        },
        dashboard: {
            defaultWidgetName: 'Widget truy vấn',
            newDashboard: 'Dashboard mới',
            saved: 'Đã thêm widget vào dashboard',
        },
        relativeTime: {
            locale: 'vi',
        },
    },
    en: {
        aiQuery: {
            autoInsertSkipped: 'The AI result is too long or schema-changing, so it was not inserted automatically.',
            autoInsertWarning: 'The AI result was not inserted automatically because it writes data, changes schema, or is too long.',
            generatedSuccess: 'SQL generated successfully!',
            generatedFailure: 'Could not generate SQL for this request.',
            requestFailed: 'AI request failed.',
            collapsedPrompt: 'Type natural language to generate SQL...',
            expandedPlaceholder: 'Describe what you want to query in natural language...',
            badge: 'AI SQL',
            title: 'AI SQL Generator',
            hotkey: 'CTRL + ENTER TO RUN',
            contextOn: 'RAG Context: ON',
            cancel: 'Cancel',
            generate: 'Generate SQL',
        },
        noSqlAi: {
            collapsedPromptRedis: 'Type natural language to generate a Redis command...',
            collapsedPromptMongo: 'Type natural language to generate MQL...',
            expandedPlaceholderRedis: 'Describe the Redis command you need...',
            expandedPlaceholderMongo: 'Describe your MongoDB query request...',
            capabilityNoteRedis: 'AI can suggest both read and write Redis commands. Be explicit when you want to set or delete keys.',
            capabilityNoteReadOnly: 'This connection is read-only, so AI should only generate find or aggregate commands for this collection.',
            capabilityNoteMutable: 'AI can generate find, aggregate, update, and delete commands. For write operations, use explicit verbs like update, delete, or remove so the workspace understands your intent.',
            quickScanSessions: 'Scan sessions',
            quickInspectTtl: 'Inspect TTL',
            quickDeleteOldKey: 'Delete old key',
            quickTopCategories: 'Top categories',
            quickLatestOrders: 'Latest orders',
            quickSamplePipeline: 'Sample pipeline',
            quickUpdateStatus: 'Update status',
            quickDeleteOldLogs: 'Delete old logs',
            safeguardExplanation: 'The AI generated a write command or a very large payload, so it was not inserted automatically. If you truly want to mutate data, mention update, delete, or remove explicitly and review the command before running it.',
            safeguardWarning: 'The NoSQL command was not inserted automatically because it may write data or is too large.',
            generatedSuccess: (commandLabel: string) => `${commandLabel} generated successfully!`,
            generatedFailure: (commandLabel: string) => `Could not generate ${commandLabel} for this request.`,
            requestFailed: 'AI request failed.',
            shortcutTitle: 'Prompt shortcuts',
            shortcutHint: 'Tap to insert',
            defaultCollection: 'Default',
            cancel: 'Cancel',
            badge: 'NoSQL AI',
            runHotkey: 'CTRL + ENTER TO RUN',
            redisCommandLabel: 'Redis command',
            mqlCommandLabel: 'MQL',
            redisGeneratorTitle: 'AI Redis Generator',
            mqlGeneratorTitle: 'AI MQL Generator',
        },
        aiAssistant: {
            newConversation: 'New conversation',
            chatHistory: 'Chat history',
            noDatabaseTitle: 'No database connected',
            noDatabaseDescription: 'Set up a Server and Database or NoSQL connection in the sidebar so AI can write more accurate queries.',
            thinking: 'Thinking...',
            disclaimer: 'AI can be wrong, so review the answer before you run anything.',
            chatCount: (count: number) => `${count} chats`,
        },
        aiChat: {
            sqlFromTab: (title: string) => `SQL from "${title}"`,
            collectionWithoutSchema: (name: string) => `Open collection: ${name} (schema analysis has not run yet)`,
            databaseContext: (connectionName: string, database: string, type: string) =>
                `Connected database: ${connectionName}, Database: ${database}, Type: ${type}`,
            attachmentOnlyPrompt: '(see attached image or context)',
            aborted: 'Stopped by user',
            error: (message: string) => `Error: ${message}`,
            noDatabaseMessage: 'No database connected. Connect first before using AI.',
            attachedSql: 'Attached SQL',
            schemaPrefix: (name: string) => `Schema for collection "${name}":`,
        },
        erd: {
            storageNotReady: 'ERD workspace storage is not ready yet',
            loadFailed: 'Failed to load ERD workspaces',
            storageDescription: 'The ERD page still works, but the backend schema must be synced before workspaces can be saved.',
        },
        queryProject: {
            title: 'Query library',
            description: 'Pin, group, and reopen queries like a lightweight IDE.',
            openLibrary: 'Open library',
            pinned: 'Pinned',
            pinHint: 'Pin queries to keep the important ones nearby.',
            recent: 'Recent',
            noHistory: 'No query runs yet.',
            run: 'Run',
            folders: 'Folders',
            noSavedQueries: 'No saved queries yet.',
            noFolder: 'No folder',
            queryCount: (count: number) => `${count} queries`,
            topTags: 'Top tags',
        },
        savedQueries: {
            title: 'Saved queries',
            description: 'Browse, preview, open, or manage saved queries.',
            searchPlaceholder: 'Search queries...',
            unknownOwner: 'Unknown owner',
            deleted: 'Saved query deleted',
            deleteFailed: 'Failed to delete saved query',
            pin: 'Pin',
            unpin: 'Unpin',
            history: 'History',
            preview: 'Preview',
            open: 'Open',
            selectToPreview: 'Select a query to preview',
            historyTitle: 'Saved query history',
            noVersions: 'No versions yet',
            name: 'Name',
        },
        saveQuery: {
            updateTitle: 'Update saved query',
            createTitle: 'Save query',
            description: 'Save or update a saved query with sharing scope and description.',
            displayName: 'Display name',
            visibility: 'Visibility',
            private: 'Private',
            workspaceWide: 'Workspace-wide',
            workspaceTeam: 'Workspace / Team',
            chooseWorkspace: 'Choose workspace',
            folderGroup: 'Folder / Group',
            tags: 'Tags (comma-separated)',
            details: 'Description',
            detailsPlaceholder: 'Short context so teammates know what this query is for.',
            cancel: 'Cancel',
            saving: 'Saving...',
            update: 'Update',
            save: 'Save query',
        },
        dashboard: {
            defaultWidgetName: 'Query Widget',
            newDashboard: 'New Dashboard',
            saved: 'Widget saved to dashboard',
        },
        relativeTime: {
            locale: 'en',
        },
    },
} as const;

export function getWorkspaceText(lang: AppLang | string | null | undefined) {
    return workspaceText[normalizeAppLang(lang)];
}

export function formatWorkspaceRelativeTime(lang: AppLang | string | null | undefined, timestamp: number) {
    const diffMinutes = Math.round((timestamp - Date.now()) / 60000);
    const absMinutes = Math.abs(diffMinutes);
    const rtf = new Intl.RelativeTimeFormat(getWorkspaceText(lang).relativeTime.locale, { numeric: 'auto' });

    if (absMinutes < 60) {
        return rtf.format(diffMinutes, 'minute');
    }

    const diffHours = Math.round(diffMinutes / 60);
    if (Math.abs(diffHours) < 24) {
        return rtf.format(diffHours, 'hour');
    }

    return rtf.format(Math.round(diffHours / 24), 'day');
}
