import { normalizeAppLang, type AppLang } from './i18n';

const workspaceText = {
    vi: {
        aiQuery: {
            autoInsertSkipped: 'Kết quả AI quá dài hoặc có thay đổi schema nên chưa được chèn tự động.',
            autoInsertWarning: 'Kết quả AI không được chèn tự động vì có thao tác ghi, đổi cấu trúc hoặc quá dài.',
            generatedSuccess: 'Đã sinh mã SQL thành công!',
            generatedFailure: 'Không thể sinh SQL cho yêu cầu này.',
            requestFailed: 'Gọi AI thất bại.',
            collapsedPrompt: 'Gõ tiếng Việt để sinh SQL, ví dụ: 10 khách hàng mới nhất...',
            expandedPlaceholder: 'Mô tả yêu cầu của bạn bằng tiếng Việt hoặc tiếng Anh...',
            badge: 'AI SQL',
            title: 'AI SQL Generator',
            hotkey: 'CTRL + ENTER để chạy',
            contextOn: 'Ngữ cảnh RAG: bật',
            cancel: 'Đóng',
            generate: 'Sinh SQL',
        },
        noSqlAi: {
            collapsedPromptRedis: 'Gõ yêu cầu để sinh lệnh Redis...',
            collapsedPromptMongo: 'Gõ yêu cầu để sinh MQL, ví dụ: lọc các đơn hàng trên 500k...',
            expandedPlaceholderRedis: 'Mô tả lệnh Redis bạn cần, ví dụ: quét session:*, lấy key user:123...',
            expandedPlaceholderMongo: 'Mô tả yêu cầu truy vấn MongoDB của bạn...',
            capabilityNoteRedis: 'AI có thể gợi ý cả lệnh đọc và ghi Redis. Hãy nói rõ nếu bạn muốn set hoặc xóa key.',
            capabilityNoteReadOnly: 'Kết nối này đang ở chế độ chỉ đọc, nên AI chỉ nên sinh find hoặc aggregate cho collection này.',
            capabilityNoteMutable: 'AI có thể sinh find, aggregate, update và delete. Với lệnh ghi dữ liệu, hãy dùng từ rõ ràng như update, delete hoặc remove để hệ thống hiểu đúng ý bạn.',
            quickScanSessions: 'Quét session',
            quickInspectTtl: 'Xem TTL key',
            quickDeleteOldKey: 'Xóa key cũ',
            quickTopCategories: 'Danh mục nhiều nhất',
            quickLatestOrders: 'Đơn mới nhất',
            quickSamplePipeline: 'Pipeline mẫu',
            quickUpdateStatus: 'Cập nhật trạng thái',
            quickDeleteOldLogs: 'Xóa log cũ',
            safeguardExplanation: 'AI đã sinh lệnh ghi dữ liệu hoặc câu lệnh quá dài nên chưa chèn tự động. Nếu bạn thật sự muốn mutate, hãy ghi rõ update, delete hoặc remove trong prompt rồi kiểm tra lại trước khi chạy.',
            safeguardWarning: 'Lệnh NoSQL chưa được chèn tự động vì có thể ghi dữ liệu hoặc quá dài.',
            generatedSuccess: (commandLabel: string) => `Đã sinh ${commandLabel} thành công!`,
            generatedFailure: (commandLabel: string) => `Không thể sinh ${commandLabel} cho yêu cầu này.`,
            requestFailed: 'Gọi AI thất bại.',
            shortcutTitle: 'Prompt gợi ý',
            shortcutHint: 'Bấm để chèn nhanh',
            defaultCollection: 'Mặc định',
            cancel: 'Đóng',
            badge: 'NoSQL AI',
            runHotkey: 'CTRL + ENTER để chạy',
            redisCommandLabel: 'lệnh Redis',
            mqlCommandLabel: 'MQL',
            redisGeneratorTitle: 'AI Redis Generator',
            mqlGeneratorTitle: 'AI MQL Generator',
            quickScanSessionsPrompt: 'Quét session:* và trả về 20 key đầu tiên khớp điều kiện.',
            quickInspectTtlPrompt: 'Hiển thị TTL của user:123 và giải thích lệnh trước khi chạy.',
            quickDeleteOldKeyPrompt: 'Xóa key cache report:daily:stale và giải thích tác động.',
            quickTopCategoriesPrompt: 'Tìm 10 category có nhiều document nhất trong collection này.',
            quickLatestOrdersPrompt: 'Lấy 20 document mới nhất, sắp xếp giảm dần theo createdAt.',
            quickSamplePipelinePrompt: 'Tạo pipeline gom nhóm document theo status và đếm từng nhóm.',
            quickUpdateStatusPrompt: 'Cập nhật tất cả document có status "pending" thành "archived" bằng updateMany và giải thích bộ lọc.',
            quickDeleteOldLogsPrompt: 'Xóa các document cũ hơn 30 ngày bằng deleteMany và giải thích bộ lọc trước khi chạy.',
            generateCommand: (commandLabel: string) => `Sinh ${commandLabel}`,
        },
        aiAssistant: {
            newConversation: 'Cuộc trò chuyện mới',
            chatHistory: 'Lịch sử chat',
            noDatabaseTitle: 'Chưa kết nối database',
            noDatabaseDescription: 'Bạn cần thiết lập Server và Database hoặc NoSQL ở sidebar để AI có thể viết query chính xác hơn.',
            thinking: 'Đang nghĩ...',
            disclaimer: 'AI có thể trả lời không chính xác, hãy kiểm tra lại trước khi chạy.',
            chatCount: (count: number) => `${count} cuộc trò chuyện`,
        },
        aiChat: {
            sqlFromTab: (title: string) => `SQL từ "${title}"`,
            collectionWithoutSchema: (name: string) => `Collection đang mở: ${name} (chưa chạy phân tích schema)`,
            databaseContext: (connectionName: string, database: string, type: string) =>
                `Database đang kết nối: ${connectionName}, Database: ${database}, Type: ${type}`,
            attachmentOnlyPrompt: '(xem hình hoặc ngữ cảnh đính kèm)',
            aborted: 'Đã dừng bởi người dùng',
            error: (message: string) => `Lỗi: ${message}`,
            noDatabaseMessage: 'Chưa kết nối database. Hãy kết nối trước khi dùng AI.',
            attachedSql: 'SQL đính kèm',
            schemaPrefix: (name: string) => `Schema cho collection "${name}":`,
        },
        erd: {
            storageNotReady: 'Kho workspace ERD chưa sẵn sàng',
            loadFailed: 'Không thể tải danh sách workspace ERD',
            storageDescription: 'Trang ERD vẫn dùng được, nhưng bạn cần sync schema backend để lưu workspace.',
            dialogTitle: 'ERD Workspaces',
            searchPlaceholder: 'Tìm workspace...',
            deleteConfirm: (workspaceName: string) => `Xóa workspace "${workspaceName}"?`,
            noWorkspaces: 'Chưa có workspace ERD nào',
            noMatches: 'Không tìm thấy workspace nào',
            preview: 'Chi tiết',
            liveLabel: 'ERD live',
            emptyPresence: 'Chưa có ai mở ERD này',
            history: 'Lịch sử',
            open: 'Mở',
            notes: 'Ghi chú',
            visibleTables: 'Bảng hiển thị',
            savedNodes: 'Node tùy chỉnh',
            manualEdges: 'Liên kết thủ công',
            selectWorkspace: 'Chọn workspace để xem trước',
            historyTitle: 'Lịch sử workspace ERD',
            noVersions: 'Chưa có phiên bản nào',
            workspaceName: 'Tên workspace',
            entities: 'Thực thể',
            selected: 'đã chọn',
            refreshMetadata: 'Làm mới metadata',
            selectDatabase: 'Chọn Cơ sở dữ liệu',
            selectSchema: 'Chọn Schema',
            allSchemas: 'Tất cả Schema',
            filterPlaceholder: 'Lọc hoặc tìm nhanh bảng...',
            all: 'Tất cả',
            none: 'Bỏ chọn',
            loadingEntities: 'Đang tải thực thể...',
            tableList: 'Danh sách bảng',
            noLocalTables: 'Không tìm thấy bảng cục bộ',
            smartSuggestions: 'Gợi ý thông minh',
            hybridResults: 'Kết quả từ Redis Hybrid Search (AI + Index)',
            globalResults: 'Kết quả từ Redis Global Index',
            clearCanvas: 'Xóa sơ đồ',
            noConnectionToSave: 'Chưa có connection để lưu workspace.',
            saved: 'Đã lưu workspace ERD',
            loaded: 'Đã mở workspace ERD',
            deleted: 'Đã xóa workspace ERD',
            metadataRefreshed: 'Đã làm mới metadata',
            metadataRefreshFailed: 'Không thể làm mới metadata',
            removeConstraintConfirm: (type: string, constraintName: string) => `Bạn có chắc muốn xóa ${type.toUpperCase()} (${constraintName}) này không?`,
            removeConstraintSuccess: (type: string) => `${type.toUpperCase()} đã được xóa thành công`,
            removeConstraintFailed: (type: string) => `Không thể xóa ${type.toUpperCase()}`,
            removeRelationshipConfirm: (constraintName: string) => `Bạn có chắc muốn xóa ràng buộc khóa ngoại (${constraintName}) này không?`,
            removeRelationshipSuccess: 'Đã xóa liên kết thành công',
            removeRelationshipFailed: 'Không thể xóa liên kết',
            relationshipCreated: 'Đã tạo liên kết',
            relationshipCreateFailed: 'Không thể tạo liên kết',
            exportedPng: 'Đã xuất PNG',
            exportedSql: 'Đã xuất SQL',
            saveDialogUpdateTitle: 'Cập nhật workspace ERD',
            saveDialogCreateTitle: 'Lưu workspace ERD',
            saveDialogError: 'Không thể lưu workspace ERD',
            saveDialogName: 'Tên workspace',
            saveDialogNamePlaceholder: 'VD: Payments schema map',
            saveDialogNotes: 'Ghi chú',
            saveDialogNotesPlaceholder: 'Mô tả ngắn để lần sau mở lại dễ hiểu hơn.',
            saveDialogCancel: 'Hủy',
            saveDialogSaving: 'Đang lưu...',
            saveDialogUpdate: 'Cập nhật',
            saveDialogSave: 'Lưu workspace',
        },
        commandPalette: {
            switchedTo: (connectionName: string, database?: string | null) => `Đã chuyển sang ${connectionName}${database ? ` (${database})` : ''}`,
            searchPlaceholder: 'Tìm kiếm bảng, view hoặc thực thi lệnh...',
            loading: 'AI đang suy nghĩ...',
            noResults: 'Không tìm thấy kết quả nào',
            suggestedCommands: 'Lệnh gợi ý',
            syncIndex: 'Đồng bộ Index',
            syncComplete: 'Đồng bộ xong',
            queryHistory: 'Thanh lịch sử',
            naturalLanguageHint: 'Dùng ngôn ngữ tự nhiên để tìm kiếm thông minh',
            searchResults: 'Kết quả tìm kiếm',
            enterToOpen: 'ENTER ĐỂ MỞ',
            navigate: 'Di chuyển',
            open: 'Mở',
        },
        adminDashboardPage: {
            adminPanel: 'Bảng quản trị',
            userManagement: 'Quản lý người dùng',
            auditLogs: 'Nhật ký hệ thống',
            usersShort: 'Người dùng',
            auditShort: 'Nhật ký',
        },
        queryProject: {
            title: 'Thư viện truy vấn',
            description: 'Chọn, ghim và mở lại truy vấn như một IDE gọn nhẹ.',
            openLibrary: 'Mở thư viện',
            pinned: 'Đã ghim',
            pinHint: 'Ghim truy vấn để giữ lại các truy vấn quan trọng.',
            recent: 'Gần đây',
            noHistory: 'Chưa có lịch sử chạy truy vấn.',
            run: 'Chạy',
            folders: 'Thư mục',
            noSavedQueries: 'Bạn chưa có truy vấn đã lưu nào.',
            noFolder: 'Không có thư mục',
            queryCount: (count: number) => `${count} truy vấn`,
            topTags: 'Tag phổ biến',
        },
        savedQueries: {
            title: 'Truy vấn đã lưu',
            description: 'Duyệt, xem trước, mở hoặc quản lý các truy vấn đã lưu.',
            searchPlaceholder: 'Tìm truy vấn...',
            unknownOwner: 'Không rõ người tạo',
            empty: 'Chưa có truy vấn đã lưu nào',
            noMatches: 'Không tìm thấy kết quả',
            firstSaveHint: 'Dùng Ctrl+S trong Query Editor để lưu truy vấn đầu tiên',
            deleted: 'Đã xóa truy vấn đã lưu',
            deleteFailed: 'Không thể xóa truy vấn đã lưu',
            pin: 'Ghim',
            unpin: 'Bỏ ghim',
            history: 'Lịch sử',
            preview: 'Xem trước',
            open: 'Mở',
            selectToPreview: 'Chọn một truy vấn để xem trước',
            historyTitle: 'Lịch sử truy vấn đã lưu',
            noVersions: 'Chưa có phiên bản nào',
            name: 'Tên',
        },
        saveQuery: {
            updateTitle: 'Cập nhật truy vấn đã lưu',
            createTitle: 'Lưu truy vấn',
            description: 'Lưu hoặc cập nhật truy vấn cùng phạm vi chia sẻ và mô tả.',
            displayName: 'Tên hiển thị',
            namePlaceholder: 'VD: Doanh thu theo tuần',
            visibility: 'Quyền hiển thị',
            private: 'Riêng tư',
            workspaceWide: 'Toàn workspace',
            workspaceTeam: 'Workspace / Team',
            chooseWorkspace: 'Chọn workspace',
            folderGroup: 'Thư mục / Nhóm',
            folderPlaceholder: 'analytics, ops, growth...',
            tags: 'Tags (phân tách bằng dấu phẩy)',
            tagsPlaceholder: 'dashboard, churn, monthly',
            details: 'Mô tả',
            detailsPlaceholder: 'Mô tả ngắn để đồng đội hiểu truy vấn này dùng làm gì.',
            cancel: 'Hủy',
            saving: 'Đang lưu...',
            update: 'Cập nhật',
            save: 'Lưu truy vấn',
            saveFailed: 'Không thể lưu truy vấn',
        },
        dashboard: {
            defaultWidgetName: 'Widget truy vấn',
            newDashboard: 'Dashboard mới',
            saved: 'Đã thêm widget vào dashboard',
        },
        dashboardPage: {
            confirmDeleteConnection: 'Bạn có chắc chắn muốn xóa kết nối này?',
            deleteConnectionFallback: 'Xóa kết nối thất bại',
            systemActor: 'Hệ thống',
            backToWelcome: 'Quay lại Chào mừng',
            databaseIntelligence: 'Thông tin Cơ sở dữ liệu',
            welcomeTitle: 'Chào mừng bạn đến với Data Explorer',
            welcomeDescription: 'Quản lý cơ sở dữ liệu, thực hiện truy vấn và trực quan hóa dữ liệu một cách dễ dàng.',
            newQueryTitle: 'Truy vấn mới',
            newQueryDescription: 'Mở trình chỉnh sửa SQL để chạy các truy vấn tùy ý.',
            newConnectionTitle: 'Kết nối mới',
            newConnectionDescription: 'Kết nối với cơ sở dữ liệu PostgreSQL hoặc MySQL mới.',
            browseDataTitle: 'Duyệt dữ liệu',
            browseDataDescription: 'Khám phá các bảng và lược đồ trong thanh bên.',
            insightsTitle: 'Thông tin chuyên sâu',
            insightsDescription: 'Xem các chỉ số, mức sử dụng bộ nhớ và xu hướng.',
            selectConnectionFirst: 'Chọn một kết nối trước',
            recentConnections: 'Kết nối gần đây',
            connect: 'Kết nối',
            shareWithTeam: 'Chia sẻ với Team',
            noConnections: 'Chưa có kết nối nào. Hãy tạo một cái để bắt đầu.',
            quickStats: 'Thống kê nhanh',
            activeConnections: 'Kết nối đang hoạt động',
            queriesRun: 'Truy vấn đã chạy',
            tablesAccessed: 'Bảng đã truy cập',
            proTipTitle: 'Mẹo hữu ích',
            proTipPrefix: 'Bạn có thể sử dụng',
            proTipSuffix: 'để mở nhanh một tab truy vấn mới từ bất kỳ đâu trong ứng dụng.',
            recentDashboards: 'Dashboards gần đây',
            widgetCount: (count: number) => `${count} widget`,
            noDashboards: 'Chưa có dashboard nào. Hãy lưu chart đầu tiên từ Query Results.',
            teamActivity: 'Hoạt động Team',
            noTeamActivity: 'Chưa có hoạt động nào trong team.',
        },
        noSqlDashboard: {
            confirmDeleteConnection: 'Bạn có chắc chắn muốn xóa kết nối này?',
            deleteConnectionFallback: 'Xóa kết nối thất bại',
            welcomeTitle: 'Chào mừng bạn đến với Data Explorer',
            welcomeDescription: 'Làm việc trơn tru với MongoDB, chạy các truy vấn MQL và xử lý khối lượng dữ liệu JSON khổng lồ một cách dễ dàng.',
            selectCollectionTitle: 'Chọn Collection',
            selectCollectionDescription: 'Mở thanh bên trái để chọn kết nối và collection làm việc.',
            newConnectionTitle: 'Kết nối mới',
            newConnectionDescription: 'Thêm một cụm MongoDB Atlas hoặc Redis mới vào quản lý.',
            browseDocumentsTitle: 'Duyệt Document',
            browseDocumentsDescription: 'Khám phá các CSDL và collection thuộc về kết nối hiện tại.',
            recentConnections: 'Kết nối NoSQL gần đây',
            open: 'Mở',
            noConnections: 'Chưa có kết nối nào. Hãy tạo một cái để bắt đầu.',
        },
        queryToolbar: {
            explain: 'Giải thích AI',
            runCompact: 'Chạy',
            runFull: 'Thực thi',
            aiShort: 'AI',
            aiSql: 'AI SQL',
            sqlSequence: 'Chuỗi SQL',
            refreshSidebar: 'Tải lại thanh bên',
            refresh: 'Tải lại',
            format: 'Định dạng',
            clear: 'Xóa',
            save: 'Lưu',
            open: 'Mở',
            history: 'Lịch sử',
            actions: 'Hành động',
            formatSql: 'Định dạng SQL',
            saveQuery: 'Lưu truy vấn',
            openSaved: 'Mở đã lưu',
            clearAll: 'Xóa tất cả',
            limit: 'Giới hạn',
            max50k: 'Tối đa 50k',
        },
        visualizePage: {
            hostLabel: 'cục bộ',
            goBack: 'Quay lại',
            addConnection: 'Thêm kết nối',
            noConnections: {
                sql: {
                    title: 'Chưa có kết nối SQL',
                    description: 'Thêm kết nối cơ sở dữ liệu SQL để bắt đầu trực quan hóa.',
                },
                nosql: {
                    title: 'Chưa có kết nối NoSQL',
                    description: 'Thêm kết nối MongoDB hoặc Redis để bắt đầu trực quan hóa.',
                },
            },
            selectConnection: {
                sql: 'Chọn kết nối SQL',
                nosql: 'Chọn kết nối NoSQL',
                description: 'Chọn một kết nối cơ sở dữ liệu để bắt đầu trực quan hóa.',
            },
            noCollectionTitle: 'Chưa chọn collection',
            noCollectionDescription: 'Mở một collection trong không gian NoSQL trước, rồi chạy query hoặc pipeline để tạo tập dữ liệu cho trang trực quan này.',
            backToNoSqlWorkspace: 'Về không gian NoSQL',
            loadingVisualizationTitle: 'Đang nạp dữ liệu trực quan',
            loadingVisualizationDescription: (collection: string) => `Đang lấy mẫu tài liệu từ collection ${collection} để dựng chart đầu tiên.`,
            noResultsTitle: 'Chưa có dữ liệu để trực quan hóa',
            noResultsErrorDescription: (collection: string, message: string) => `Không thể nạp dữ liệu mẫu cho ${collection}: ${message}`,
            noResultsEmptyDescription: (collection: string) => `Collection ${collection} chưa có tài liệu phù hợp để dựng chart. Hãy chạy query khác hoặc kiểm tra dữ liệu nguồn.`,
            retrySampleLoad: 'Thử nạp lại',
            backToNoSqlEditor: 'Về trình soạn NoSQL',
            noSqlTitle: 'Trực quan NoSQL',
            noSqlDescription: 'Trang riêng để rút insight từ tập kết quả hiện tại, không còn chèn trong MQL editor.',
            documents: 'tài liệu',
            chartHint: 'Nếu cần nhóm toàn collection hoặc metric phức tạp hơn, hãy quay về Aggregation Builder, chạy pipeline rồi mở lại trang này.',
            chartStudio: 'Studio trực quan',
        },
        explorerSidebar: {
            syncFailed: 'Đồng bộ thất bại',
            refreshingHierarchy: 'Đang làm mới dữ liệu...',
            refreshed: 'Đã cập nhật',
            syncingIndex: 'Đang đồng bộ index...',
            indexSynced: 'Đã đồng bộ!',
            switchedToConnection: (connectionName: string) => `Đã chuyển sang kết nối ${connectionName}`,
            title: 'Trình duyệt',
            localSearchPlaceholder: 'Tìm đối tượng...',
            globalSearchPlaceholder: 'Tìm kiếm toàn cục...',
            localInstance: 'Máy cục bộ',
            connected: 'Đang kết nối',
        },
        connectionSelector: {
            confirmDeleteConnection: 'Bạn có chắc chắn muốn xóa kết nối này không?',
            deleteConnectionFallback: 'Lỗi khi xóa kết nối',
            selectInstance: 'Chọn cơ sở dữ liệu',
            noSqlInstances: 'Cơ sở dữ liệu NoSQL',
            sqlInstances: 'Cơ sở dữ liệu SQL',
            availableInstances: 'Cơ sở dữ liệu hiện có',
            provisionServer: 'Thêm máy chủ mới',
            unknownHealth: 'không xác định',
            readOnly: 'Chỉ đọc',
            check: 'Kiểm tra',
        },
        noSqlSidebar: {
            searchPlaceholder: 'Tìm document/collection...',
            onlySupports: 'Không gian NoSQL chỉ hỗ trợ kết nối MongoDB hoặc Redis.',
            currentSelection: (type: string) => `Bạn đang chọn: ${type}`,
            scanningBson: 'Đang quét BSON',
            noCollectionsFound: 'Không tìm thấy collection',
            connected: 'Kết nối NoSQL',
        },
        noSqlMainContent: {
            executionDisabledGuardrail: 'Kết nối này đang tắt quyền chạy truy vấn.',
            readOnlyGuardrail: 'Chế độ chỉ đọc đang bật. Chỉ cho phép find/aggregate.',
            performanceGuardrail: 'Kết quả được giới hạn để bảo vệ hiệu năng và tránh quá tải.',
            gridTitle: 'Kết quả dạng bảng',
            gridDescription: 'Xem tài liệu dưới dạng cột để lọc, so sánh và scan nhanh.',
            insightsTitle: 'Insight từ tập kết quả',
            insightsDescription: 'Nhóm dữ liệu hiện tại thành metric có ý nghĩa thay vì vẽ từng document rời rạc.',
            schemaTitle: 'Phân tích schema',
            schemaDescription: 'Kiểm tra độ phủ field, kiểu dữ liệu và ví dụ giá trị trong collection.',
            pipelineOutputTitle: 'Kết quả pipeline',
            treeTitle: 'Kết quả dạng cây',
            treeDescription: 'Giữ nguyên cấu trúc BSON/JSON để kiểm tra document thật.',
            docsLabel: 'tài liệu',
            waitingTitle: 'NoSQL workspace đang chờ kết nối phù hợp...',
            waitingDescription: 'Bạn đang chọn một kết nối SQL. Hãy chọn MongoDB hoặc Redis ở sidebar để mở NoSQL Studio.',
            guardrailsTitle: 'Guardrails NoSQL',
            closeCollection: 'Đóng collection',
            aggregationBuilder: 'Trình dựng Aggregation Pipeline',
            visualBuilder: 'Trình thiết kế truy vấn (MQL)',
            formatHint: 'Shift + Alt + F để định dạng',
            askAiMql: 'Hỏi trợ lý AI sinh MQL',
            capped: 'Giới hạn',
            hideResultsPanelTitle: 'Ẩn panel kết quả',
            showResultsPanelTitle: 'Mở panel kết quả',
            hideResults: 'Ẩn kết quả',
            showResults: 'Mở kết quả',
            run: 'Thực thi',
            closeResultsPanel: 'Đóng panel kết quả (Ctrl+J)',
            queryingBson: 'Đang truy vấn BSON...',
            buildPipelineHint: 'Dựng pipeline rồi chạy để xem kết quả',
            clickRunHint: 'Nhấn Thực thi để nạp dữ liệu',
        },
        queryResults: {
            failed: 'TRUY VẤN THẤT BẠI',
            empty: 'Chạy truy vấn để xem kết quả',
            dataCompact: 'Dữ liệu',
            dataFull: 'Kết quả dữ liệu',
            messagesCompact: 'T.Báo',
            messagesFull: 'Thông báo',
            planCompact: 'Sơ đồ',
            planFull: 'Sơ đồ truy vấn',
            timePrefix: 'Thời gian: ',
            clearResults: 'Xóa kết quả (Clear)',
            saveToDashboard: 'Lưu vào dashboard',
            closePanel: 'Đóng bảng (Ctrl+J)',
            error: 'LỖI:',
            success: 'TRUY VẤN THỰC THI THÀNH CÔNG.',
            rowsAffected: 'SỐ DÒNG ẢNH HƯỞNG:',
            columnsReturned: 'SỐ CỘT TRẢ VỀ:',
            executionTime: 'THỜI GIAN THỰC THI:',
            completedAt: 'HOÀN THÀNH LÚC:',
            sqlStatement: 'CÂU LỆNH SQL:',
            noMessages: 'Không có thông báo nào.',
        },
        queryEditor: {
            explainPrompt: 'Giải thích câu SQL này theo đúng thứ tự thực thi. Không sinh SQL mới. Trả lời bằng markdown với các phần: Tóm tắt tổng thể, Giải thích từng bước, và Lưu ý/rủi ro nếu có. Nếu là nhiều statement, hãy giải thích lần lượt từng statement.',
            readOnlyGuardrail: 'Kết nối đang ở chế độ chỉ đọc',
            executionDisabledGuardrail: 'đã tắt chạy truy vấn',
            serverGuardrail: (rows: string) => `bộ bảo vệ máy chủ: tối đa ${rows} dòng`,
            requestedLimit: (rows: string | number) => `giới hạn yêu cầu: ${rows} dòng`,
            timeoutGuardrail: 'timeout ~30s',
            savedQueryUpdated: 'Đã cập nhật truy vấn đã lưu',
            defaultQueryName: (dateLabel: string) => `Truy vấn ${dateLabel}`,
            querySaved: 'Đã lưu truy vấn',
            presenceLabel: 'Truy vấn đang mở',
            presenceEmpty: 'Chưa ai mở truy vấn này',
            blockedReadOnly: 'Truy vấn bị chặn bởi chế độ chỉ đọc',
            blockedPolicy: 'Truy vấn bị chặn bởi policy kết nối',
            connectionGuardrails: 'Guardrails kết nối',
        },
        app: {
            routeLoading: 'Đang tải...',
        },
        navMainActions: {
            insights: 'Chi tiết',
            visualize: 'Trực quan',
            diagram: 'Sơ đồ',
        },
        navbar: {
            teams: 'Nhóm',
        },
        navMenus: {
            file: 'Tệp',
            fileOperations: 'Thao tác tệp',
            newQuery: 'Truy vấn mới',
            duplicateTab: 'Nhân bản tab',
            closeAllTabs: 'Đóng tất cả tab',
            edit: 'Sửa',
            undo: 'Hoàn tác',
            redo: 'Làm lại',
            cut: 'Cắt',
            copy: 'Sao chép',
            paste: 'Dán',
            view: 'Xem',
            hideSidebar: 'Ẩn thanh bên',
            showSidebar: 'Hiện thanh bên',
            hideResultPanel: 'Ẩn bảng kết quả',
            showResultPanel: 'Hiện bảng kết quả',
            toggleFullScreen: 'Bật/tắt toàn màn hình',
            help: 'Trợ giúp',
            documentation: 'Tài liệu hướng dẫn',
            checkUpdates: 'Kiểm tra cập nhật...',
            globalShortcuts: 'Phím tắt chung: Ctrl+N, Ctrl+I, Ctrl+B, Ctrl+J',
        },
        navUserSection: {
            aiAssistantTitle: 'AI Assistant (Ctrl+I)',
            turnOffDesktopMode: 'Tắt chế độ máy tính',
            turnOnDesktopMode: 'Bật chế độ máy tính',
            profile: 'Hồ sơ',
            billing: 'Gói cước',
            settings: 'Cài đặt',
            teams: 'Nhóm / Team',
            adminPanel: 'Bảng quản trị',
            logOut: 'Đăng xuất',
        },
        queryHistory: {
            title: 'Lịch sử truy vấn',
            entryCount: (count: number) => `${count} mục`,
            refresh: 'Tải lại',
            description: 'Xem lịch sử truy vấn đã chạy, tìm kiếm lại và mở nhanh vào editor.',
            unknownQuery: 'Truy vấn không xác định',
            searchPlaceholder: 'Tìm kiếm truy vấn...',
            clearAll: 'Xóa tất cả',
            loading: 'Đang tải lịch sử...',
            empty: 'Chưa có truy vấn nào',
            noMatches: 'Không tìm thấy kết quả',
            rowsLabel: 'dòng',
            synced: 'Đã đồng bộ',
            databaseFallback: 'Cơ sở dữ liệu',
            openInEditor: 'Mở trong editor',
            copySql: 'Sao chép SQL',
            timeLocale: 'vi-VN',
        },
        sqlSequence: {
            title: 'Chuỗi SQL',
            description: 'Sắp xếp lại từng khối SQL và chạy tuần tự theo thứ tự bạn chọn.',
            reorderHint: 'Kéo từng khối để đổi thứ tự, hoặc dùng nút lên xuống.',
            addStep: 'Thêm bước',
            dragToReorder: 'Kéo để đổi thứ tự',
            step: 'Bước',
            moveUp: 'Đưa lên',
            moveDown: 'Đưa xuống',
            deleteStep: 'Xóa bước',
            sqlPlaceholder: 'Nhập SQL cho bước này...',
            nonEmptySteps: (count: number) => `${count} bước có nội dung`,
            close: 'Đóng',
            applyToEditor: 'Áp vào editor',
            runSequence: 'Chạy tuần tự',
        },
        aiQueryExplanation: {
            title: 'AI Giải thích truy vấn',
            description: 'AI sẽ diễn giải câu SQL theo từng phần, nêu mục đích và các lưu ý nếu có.',
            query: 'Truy vấn',
            explanation: 'Giải thích',
            loading: 'AI đang phân tích câu SQL này...',
            fallback: 'AI chưa trả về phần giải thích.',
            close: 'Đóng',
        },
        noSqlQuery: {
            noActiveConnection: 'Chưa có kết nối hoạt động',
            executionDisabled: 'Kết nối này đang tắt chạy truy vấn',
            selectCollection: 'Hãy chọn collection trước',
            payloadObjectRequired: 'Payload MQL phải là một object JSON',
            invalidJson: 'JSON MQL không hợp lệ',
            missingActionCollection: 'JSON MQL phải có trường "action" và "collection"',
            readOnlyViolation: 'Kết nối này là chỉ đọc. Chỉ cho phép find và aggregate.',
            pipelineResults: 'kết quả pipeline',
            documents: 'tài liệu',
            requestedLimitHint: (limit: string, noun: string) => `Đang hiển thị ${limit} ${noun} đầu tiên theo giới hạn bạn yêu cầu.`,
            guardrailLimitHint: (limit: string, noun: string) => `Đang hiển thị ${limit} ${noun} đầu tiên vì bộ bảo vệ hiệu năng đã chặn phần còn lại.`,
            resultsLabel: 'kết quả',
            countLabel: 'đếm',
            insertedLabel: 'đã thêm',
            updatedLabel: 'đã sửa',
            deletedLabel: 'đã xóa',
            valuesLabel: 'giá trị',
            docsLabel: 'tài liệu',
            loadedPipeline: (count: number, durationMs: number) => `Đã nạp ${count} kết quả pipeline (${durationMs}ms)`,
            countedDocuments: (count: number, durationMs: number) => `Đếm được ${count} tài liệu (${durationMs}ms)`,
            insertedOne: (durationMs: number) => `Đã thêm 1 tài liệu (${durationMs}ms)`,
            insertedMany: (count: number, durationMs: number) => `Đã thêm ${count} tài liệu (${durationMs}ms)`,
            matchedHint: (count: number) => `${count} tài liệu khớp điều kiện`,
            updatedDocuments: (count: number, durationMs: number) => `Đã cập nhật ${count} tài liệu (${durationMs}ms)`,
            deletedDocuments: (count: number, durationMs: number) => `Đã xóa ${count} tài liệu (${durationMs}ms)`,
            loadedDistinct: (count: number, durationMs: number) => `Đã lấy ${count} giá trị distinct (${durationMs}ms)`,
            loadedDocuments: (count: number, durationMs: number) => `Đã nạp ${count} tài liệu (${durationMs}ms)`,
            executionFailed: 'Thực thi MQL thất bại',
        },
        jsonTreeView: {
            copyValue: 'Sao chép giá trị',
            copyObject: 'Sao chép đối tượng',
            itemCount: (count: number) => `${count} phần tử`,
            keyCount: (count: number) => `${count} khóa`,
        },
        noSqlVisualize: {
            documentCount: 'Số lượng tài liệu',
            sum: 'Tổng',
            average: 'Trung bình',
            minimum: 'Nhỏ nhất',
            maximum: 'Lớn nhất',
            numericFieldFallback: 'trường số',
            countShort: 'Số lượng',
            bucket: 'Nhóm',
            empty: 'Chưa có dữ liệu để trực quan hóa.',
            notChartReadyTitle: 'Tập kết quả này chưa phù hợp để nhóm trực quan.',
            notChartReadyDescription: 'Hãy dùng Aggregation Builder để tạo pipeline có field nhóm rõ ràng, hoặc chuyển sang Grid để kiểm tra dữ liệu thô.',
            currentSample: 'Mẫu hiện tại',
            documentsFrom: (collection: string) => `tài liệu từ ${collection}`,
            groupingFields: 'Nhóm khả dụng',
            bestDefault: (field: string) => `Gợi ý mạnh nhất: ${field}`,
            noStrongGrouping: 'Chưa có field nhóm phù hợp.',
            numericMetrics: 'Metric số',
            usingDocumentCount: 'Đang dùng đếm tài liệu.',
            topBucket: 'Nhóm nổi bật',
            noTopBucket: 'Chưa có nhóm nổi bật.',
            groupBy: 'Nhóm theo',
            groupFieldPlaceholder: 'Chọn field nhóm',
            metric: 'Metric',
            metricPlaceholder: 'Chọn metric',
            countMetric: 'Đếm tài liệu',
            numericField: 'Field số',
            notNeededForCount: 'Không cần cho Count',
            numericFieldPlaceholder: 'Chọn field số',
            insightHint: 'Visualize giờ dùng để rút insight nhanh từ tập kết quả hiện tại. Nếu bạn cần số liệu toàn collection hoặc group phức tạp hơn, hãy dùng Aggregation Builder với $group trước rồi quay lại đây.',
            compareBy: (field: string) => `So sánh theo ${field}`,
            insufficientNumericData: 'Không đủ dữ liệu số cho metric hiện tại. Hãy đổi sang Count hoặc chọn field số khác.',
            collectionFallback: 'collection',
            currentCollectionFallback: 'collection hiện tại',
        },
        aiMessageBubble: {
            confirmDelete: 'Xóa tin nhắn này?',
            cancelEdit: 'Hủy',
            saveAndSend: 'Lưu & Gửi',
            insertToEditor: 'Chèn vào editor',
            runNow: 'Chạy ngay',
            copySql: 'Sao chép SQL',
            copyMql: 'Sao chép MQL',
            suggestedChart: 'Biểu đồ gợi ý',
            insertSuggestion: 'Chèn gợi ý vào editor',
            runSuggestion: 'Chạy gợi ý',
            copySuggestion: 'Sao chép gợi ý',
            editMessage: 'Chỉnh sửa',
            copyMessage: 'Sao chép',
        },
        forgotPassword: {
            otpSent: 'Đã gửi mã OTP đến email của bạn!',
            resetSuccess: 'Đổi mật khẩu thành công!',
            sendOtpError: 'Lỗi khi gửi OTP',
            invalidOtp: 'OTP không hợp lệ',
            forgotTitle: 'Quên mật khẩu',
            resetTitle: 'Đặt lại mật khẩu',
            forgotDescription: 'Nhập email của bạn để nhận mã xác thực',
            resetDescription: 'Nhập mã OTP (6 số) được gửi đến email của bạn',
            sendOtp: 'Gửi mã OTP',
            otpLabel: 'Mã OTP / OTP Code',
            newPasswordLabel: 'Mật khẩu mới / New Password',
            resetPassword: 'Đặt lại mật khẩu',
            backToLogin: 'Quay lại đăng nhập',
        },
        landingPage: {
            seoTitle: 'Data Explorer - IDE Cơ sở dữ liệu Thông minh',
            seoDescription: 'Khám phá và quản lý SQL & NoSQL với sức mạnh của AI. Trình duyệt cơ sở dữ liệu hiện đại, nhanh chóng và bảo mật.',
        },
        landingHeader: {
            backToTopAria: 'Quay lên đầu trang',
            features: 'Tính năng',
            liveDemo: 'Bản demo',
            pricing: 'Giá cả',
            docs: 'Tài liệu',
            changelog: 'Cập nhật',
            goBack: 'Quay lại',
            logout: 'Đăng xuất',
            workspace: 'Workspace',
            login: 'Đăng nhập',
            startAnalysis: 'Bắt đầu',
            toggleMenuAria: 'Bật/tắt menu',
        },
        landingFooter: {
            product: 'Sản phẩm',
            resources: 'Tài nguyên',
            legal: 'Pháp lý',
            productLinks: ['Tính năng', 'Gemini 3.1', 'ERD trực quan', 'Nhật ký thay đổi'],
            resourceLinks: ['Tài liệu', 'Clean Code Guide', 'Vitest Suite', 'Trạng thái'],
            legalLinks: ['Quyền riêng tư', 'Điều khoản', 'Bảo mật AES', 'Tuân thủ'],
            brandDescription: 'Bộ công cụ dữ liệu được thiết kế chính xác cho thế hệ kỹ sư tiếp theo. Xây trên nền tốc độ và bảo mật.',
            builtForTeams: 'XÂY DỰNG CHO NHÓM DỮ LIỆU HIỆN ĐẠI.',
            liveStatus: 'Trạng thái: Hoạt động',
            languageLabel: 'Tiếng Việt',
        },
        workflowSection: {
            title: 'Quy trình Thông minh',
            description: 'Sự kết hợp hoàn hảo giữa con người và trí tuệ nhân tạo.',
            steps: [
                { title: 'Khám phá', description: 'Tự động quét và lập chỉ mục toàn bộ lược đồ dữ liệu của bạn.' },
                { title: 'Xử lý AI', description: 'Gemini 3.1 phân tích ngữ cảnh và tối ưu hóa câu lệnh SQL.' },
                { title: 'Thực thi', description: 'Phản hồi trong tích tắc với kết quả được trực quan hóa.' },
                { title: 'Lưu trữ & Đồng bộ', description: 'Mã hóa AES-256 và đồng bộ hóa an toàn trên các thiết bị.' },
            ],
        },
        featuresSection: {
            title: 'Trí tuệ hợp nhất',
            description: 'Không chỉ là một trình chỉnh sửa. Đó là trung tâm chỉ huy cho dữ liệu của bạn, được xây dựng với sự tinh xảo hiện đại.',
            features: [
                {
                    title: 'Monaco Editor',
                    description: 'Trình soạn thảo mã chuyên nghiệp với Auto-complete, gợi ý cấu trúc bảng trực tiếp bằng AI và Schema Intellisense.',
                },
                {
                    title: 'Hỗ trợ SQL & NoSQL Toàn diện',
                    description: 'Trải nghiệm đồng nhất giữa PostgreSQL, MySQL và MongoDB với bộ phím tắt, menu và công cụ Trực quan hóa dùng chung.',
                },
                {
                    title: 'Live ERD Visualizer',
                    description: 'Tự động phân tích và tạo sơ đồ quan hệ (ERD) bằng React Flow. Cung cấp góc nhìn tổng quan rõ ràng về kiến trúc database.',
                },
                {
                    title: 'Gemini 3.1 AI Agent',
                    description: 'AI Assistant phân tích ngữ cảnh, giúp bạn tạo SQL bằng ngôn ngữ tự nhiên hoặc sửa lỗi tối ưu hóa query.',
                },
                {
                    title: 'Bảo mật & Phân quyền',
                    description: 'Bảo mật đa lớp: chặn SQL injection lồng nhau, triệt phá SSRF qua tunnel, siết riêng tư team và mã hóa AES-256-GCM.',
                },
                {
                    title: 'Lịch sử & Export',
                    description: 'Giám sát thời gian thực thi, giữ lại lịch sử câu lệnh và hỗ trợ xuất dữ liệu ra CSV, JSON hoặc script SQL.',
                },
            ],
        },
        heroSection: {
            titlePrefix: 'HỆ QUẢN TRỊ',
            titleHighlight: 'CƠ SỞ DỮ LIỆU BẰNG AI',
            description: 'Thay thế các công cụ cũ kĩ. Kết nối SQL & NoSQL, bảo mật đa lớp chuẩn doanh nghiệp (SSRF & SQL Guard), và viết query siêu tốc cùng AI Assistant.',
            openWorkspace: 'Vào Workspace',
            claimAccess: 'Nhận quyền truy cập',
            documentation: 'Tài liệu hướng dẫn',
        },
        aiSpotlight: {
            titleLine1: 'Trợ lý Dữ liệu',
            titleLine2: 'AI Đa Phương Thức.',
            description: 'Phân tích tự động data schema của bạn. Dùng ngôn ngữ tự nhiên để truy vấn dữ liệu phức tạp. Với multimodal vision, AI còn có thể đọc sơ đồ ERD bằng hình ảnh và tái tạo cấu trúc DB.',
            talkToAssistant: 'Trò chuyện với Trợ lý',
            learnHowItWorks: 'Tìm hiểu cách hoạt động',
        },
        docsCta: {
            title: 'Bạn đã sẵn sàng đi sâu hơn?',
            description: 'Tài liệu toàn diện của chúng tôi bao gồm mọi thứ từ thiết lập ban đầu đến kỹ thuật AI nâng cao.',
            apiReference: 'Tham chiếu API',
            architecture: 'Kiến trúc',
            openDocumentation: 'Mở Tài liệu',
        },
        pricingSection: {
            title: 'Giá rõ ràng cho database workspace',
            description: 'Thanh toán bằng VND qua MoMo và ZaloPay. Giá USD chỉ dùng để tham khảo.',
            bestValue: 'Đáng giá nhất',
            openWorkspace: 'Mở workspace',
            upgradeInProfile: 'Nâng cấp trong hồ sơ',
            footerNote: 'MoMo và ZaloPay chỉ kích hoạt Pro sau khi webhook từ nhà cung cấp xác nhận thành công.',
        },
        documentationPage: {
            defaultTitle: 'Tài liệu',
            seoTitle: (itemTitle: string) => `${itemTitle}`,
            seoDescription: (itemTitle: string) => `Hướng dẫn chi tiết về ${itemTitle} trong Data Explorer. Tìm hiểu cách tối ưu hóa quy trình làm việc với dữ liệu.`,
            docsLabel: 'Tài liệu',
            quickSearch: 'Tìm nhanh tài liệu...',
            goBack: 'Quay lại',
            launchApp: 'Mở Ứng dụng',
            editPage: 'Chỉnh sửa trang này',
            releaseDate: 'Tháng 6 2026',
            helpful: 'Tài liệu này hữu ích chứ?',
            readyTitle: 'Sẵn sàng khám phá dữ liệu?',
            readyDescription: 'Tham gia cộng đồng trên GitHub để đóng góp cho IDE cơ sở dữ liệu địa phương thông minh nhất.',
            tableOfContents: 'Mục lục',
            noHeadings: 'Không có đề mục nào',
        },
        usersView: {
            loadFailed: 'Không thể tải danh sách người dùng',
            roleUpdated: (role: string) => `Đã cập nhật vai trò thành ${role}`,
            passwordPrompt: 'Nhập mật khẩu mới (ít nhất 6 ký tự):',
            passwordTooShort: 'Mật khẩu phải dài ít nhất 6 ký tự',
            passwordResetSuccess: 'Đã đặt lại mật khẩu thành công',
            deleteConfirm: (email: string) => `Bạn có chắc chắn muốn xóa người dùng ${email}?`,
            userDeleted: 'Đã xóa người dùng thành công',
            loading: 'Đang tải...',
            demoteTitle: 'Hạ quyền về người dùng',
            promoteTitle: 'Nâng quyền lên quản trị',
            demote: 'Hạ quyền',
            promote: 'Nâng quyền',
            unbanTitle: 'Mở khóa người dùng',
            banTitle: 'Khóa người dùng',
            unban: 'Mở khóa',
            ban: 'Khóa',
            resetPassword: 'Đặt lại mật khẩu',
            reset: 'Đặt lại',
            deleteUser: 'Xóa người dùng',
            delete: 'Xóa',
            noName: 'Chưa đặt tên',
            banned: 'Bị khóa',
            role: 'Vai trò',
            admin: 'Quản trị',
            user: 'Người dùng',
            joined: 'Ngày tham gia',
            name: 'Tên',
            joinedDate: 'Ngày tham gia',
            actions: 'Hành động',
            noUsers: 'Không có người dùng nào.',
        },
        auditLogsView: {
            security: 'Bảo mật',
            data: 'Dữ liệu',
            team: 'Nhóm',
            user: 'Người dùng',
            system: 'Hệ thống',
            other: 'Khác',
            loading: 'Đang tải nhật ký...',
            searchPlaceholder: 'Tìm kiếm hành động hoặc người dùng...',
            all: 'Tất cả',
            noMatches: 'Không tìm thấy nhật ký nào phù hợp.',
            userLabel: 'Người dùng',
            systemActor: 'Hệ thống',
            ipAndTime: 'IP và thời gian',
            action: 'Hành động',
            ipAndDevice: 'IP & thiết bị',
            time: 'Thời gian',
            detailsTitle: 'Chi tiết nhật ký',
            location: 'Địa chỉ',
            extendedData: 'Dữ liệu chi tiết',
            noExtendedData: 'Không có dữ liệu chi tiết',
            unknown: 'không rõ',
        },
        shareConnectionDialog: {
            sharedSuccess: 'Đã chia sẻ kết nối với team!',
            shareFailed: 'Lỗi khi chia sẻ kết nối',
            createTeamPrompt: 'Nhập tên team mới:',
            createTeamFailed: 'Lỗi khi tạo team',
            title: 'Chia sẻ kết nối với team',
            description: 'Chọn team và teamspace để đưa connection này vào đúng workspace chung.',
            selectTeam: 'Chọn Team',
            selectTeamPlaceholder: 'Chọn một team...',
            noTeams: 'Bạn chưa tham gia team nào',
            selectTeamspace: 'Chọn Teamspace',
            optional: 'Tùy chọn...',
            unassigned: 'Không chọn teamspace',
            createNewTeam: 'Tạo team mới',
            cancel: 'Hủy',
            shareNow: 'Chia sẻ ngay',
        },
        bulkImportDialog: {
            csvOnly: 'Vui lòng chọn file CSV',
            invalidCsv: 'File CSV trống hoặc không đúng định dạng',
            importSuccess: (count: number) => `Đã nhập ${count} dòng thành công!`,
            importFailed: 'Lỗi khi nhập dữ liệu',
            fallbackImportError: 'Import thất bại',
            title: 'Nhập dữ liệu hàng loạt',
            dropHere: 'Thả file vào đây',
            dragHere: 'Kéo thả file CSV vào đây',
            browseHint: 'Hoặc click để chọn từ máy tính',
            selectFile: 'Chọn File',
            rowsReady: (count: number) => `${count} dòng dữ liệu sẵn sàng`,
            changeFile: 'Chọn file khác',
            readOnlyBlocked: 'Kết nối đang ở chế độ chỉ đọc nên không thể import.',
            disabledBlocked: 'Import/export đã bị tắt cho kết nối này.',
            cancel: 'Hủy',
            startImport: 'Bắt đầu nhập',
        },
        foreignKeyDialog: {
            title: 'Tạo Liên kết Khóa ngoại',
            description: (sourceTable: string, targetTable: string) => `Xác định mối quan hệ giữa ${sourceTable} và ${targetTable}.`,
            constraintName: 'Tên ràng buộc',
            childTable: 'Bảng Khóa ngoại (Con)',
            parentTable: 'Bảng Khóa chính (Cha)',
            table: 'Bảng',
            column: 'Cột',
            refs: 'Tham chiếu',
            onDelete: 'Khi xóa',
            onUpdate: 'Khi cập nhật',
            warning: 'Việc tạo mối quan hệ này sẽ thay đổi cấu trúc cơ sở dữ liệu của bạn. Hãy đảm bảo rằng dữ liệu hiện tại không vi phạm ràng buộc mới này, nếu không thao tác sẽ thất bại.',
            cancel: 'Hủy',
            createRelationship: 'Tạo Liên kết',
        },
        relativeTime: {
            locale: 'vi',
        },
    },
    en: {
        aiQuery: {
            autoInsertSkipped: 'The AI result is too long or schema-changing, so it was not inserted automatically.',
            autoInsertWarning: 'The AI result was not inserted automatically because it writes data, changes schema, or is too long.',
            generatedSuccess: 'SQL generated successfully!',
            generatedFailure: 'Could not generate SQL for this request.',
            requestFailed: 'AI request failed.',
            collapsedPrompt: 'Type natural language to generate SQL...',
            expandedPlaceholder: 'Describe what you want to query in natural language...',
            badge: 'AI SQL',
            title: 'AI SQL Generator',
            hotkey: 'CTRL + ENTER TO RUN',
            contextOn: 'RAG Context: ON',
            cancel: 'Cancel',
            generate: 'Generate SQL',
        },
        noSqlAi: {
            collapsedPromptRedis: 'Type natural language to generate a Redis command...',
            collapsedPromptMongo: 'Type natural language to generate MQL...',
            expandedPlaceholderRedis: 'Describe the Redis command you need...',
            expandedPlaceholderMongo: 'Describe your MongoDB query request...',
            capabilityNoteRedis: 'AI can suggest both read and write Redis commands. Be explicit when you want to set or delete keys.',
            capabilityNoteReadOnly: 'This connection is read-only, so AI should only generate find or aggregate commands for this collection.',
            capabilityNoteMutable: 'AI can generate find, aggregate, update, and delete commands. For write operations, use explicit verbs like update, delete, or remove so the workspace understands your intent.',
            quickScanSessions: 'Scan sessions',
            quickInspectTtl: 'Inspect TTL',
            quickDeleteOldKey: 'Delete old key',
            quickTopCategories: 'Top categories',
            quickLatestOrders: 'Latest orders',
            quickSamplePipeline: 'Sample pipeline',
            quickUpdateStatus: 'Update status',
            quickDeleteOldLogs: 'Delete old logs',
            safeguardExplanation: 'The AI generated a write command or a very large payload, so it was not inserted automatically. If you truly want to mutate data, mention update, delete, or remove explicitly and review the command before running it.',
            safeguardWarning: 'The NoSQL command was not inserted automatically because it may write data or is too large.',
            generatedSuccess: (commandLabel: string) => `${commandLabel} generated successfully!`,
            generatedFailure: (commandLabel: string) => `Could not generate ${commandLabel} for this request.`,
            requestFailed: 'AI request failed.',
            shortcutTitle: 'Prompt shortcuts',
            shortcutHint: 'Tap to insert',
            defaultCollection: 'Default',
            cancel: 'Cancel',
            badge: 'NoSQL AI',
            runHotkey: 'CTRL + ENTER TO RUN',
            redisCommandLabel: 'Redis command',
            mqlCommandLabel: 'MQL',
            redisGeneratorTitle: 'AI Redis Generator',
            mqlGeneratorTitle: 'AI MQL Generator',
            quickScanSessionsPrompt: 'Scan session:* and return the first 20 matching keys.',
            quickInspectTtlPrompt: 'Show the TTL for user:123 and explain the command before running it.',
            quickDeleteOldKeyPrompt: 'Delete the cache key report:daily:stale and explain the impact.',
            quickTopCategoriesPrompt: 'Find the top 10 categories by document count in this collection.',
            quickLatestOrdersPrompt: 'Find the latest 20 documents sorted by createdAt descending.',
            quickSamplePipelinePrompt: 'Build an aggregation pipeline that groups documents by status and counts each group.',
            quickUpdateStatusPrompt: 'Update all documents with status "pending" to "archived" using updateMany and explain the filter.',
            quickDeleteOldLogsPrompt: 'Delete documents older than 30 days using deleteMany and explain the filter before running it.',
            generateCommand: (commandLabel: string) => `Generate ${commandLabel}`,
        },
        aiAssistant: {
            newConversation: 'New conversation',
            chatHistory: 'Chat history',
            noDatabaseTitle: 'No database connected',
            noDatabaseDescription: 'Set up a Server and Database or NoSQL connection in the sidebar so AI can write more accurate queries.',
            thinking: 'Thinking...',
            disclaimer: 'AI can be wrong, so review the answer before you run anything.',
            chatCount: (count: number) => `${count} chats`,
        },
        aiChat: {
            sqlFromTab: (title: string) => `SQL from "${title}"`,
            collectionWithoutSchema: (name: string) => `Open collection: ${name} (schema analysis has not run yet)`,
            databaseContext: (connectionName: string, database: string, type: string) =>
                `Connected database: ${connectionName}, Database: ${database}, Type: ${type}`,
            attachmentOnlyPrompt: '(see attached image or context)',
            aborted: 'Stopped by user',
            error: (message: string) => `Error: ${message}`,
            noDatabaseMessage: 'No database connected. Connect first before using AI.',
            attachedSql: 'Attached SQL',
            schemaPrefix: (name: string) => `Schema for collection "${name}":`,
        },
        erd: {
            storageNotReady: 'ERD workspace storage is not ready yet',
            loadFailed: 'Failed to load ERD workspaces',
            storageDescription: 'The ERD page still works, but the backend schema must be synced before workspaces can be saved.',
            dialogTitle: 'ERD Workspaces',
            searchPlaceholder: 'Search workspaces...',
            deleteConfirm: (workspaceName: string) => `Delete workspace "${workspaceName}"?`,
            noWorkspaces: 'No ERD workspaces yet',
            noMatches: 'No matches found',
            preview: 'Preview',
            liveLabel: 'ERD live',
            emptyPresence: 'No one on this ERD',
            history: 'History',
            open: 'Open',
            notes: 'Notes',
            visibleTables: 'Visible tables',
            savedNodes: 'Saved nodes',
            manualEdges: 'Manual edges',
            selectWorkspace: 'Select a workspace to preview',
            historyTitle: 'ERD Workspace History',
            noVersions: 'No versions yet',
            workspaceName: 'Workspace name',
            entities: 'Entities',
            selected: 'selected',
            refreshMetadata: 'Refresh Metadata',
            selectDatabase: 'Select Database',
            selectSchema: 'Select Schema',
            allSchemas: 'All Schemas',
            filterPlaceholder: 'Filter or quick find tables...',
            all: 'All',
            none: 'None',
            loadingEntities: 'Exploring Entities...',
            tableList: 'Table List',
            noLocalTables: 'No local tables found',
            smartSuggestions: 'Smart Suggestions',
            hybridResults: 'Results from Redis Hybrid Search (AI + Index)',
            globalResults: 'Results from Redis Global Index',
            clearCanvas: 'Clear Canvas',
            noConnectionToSave: 'No connection selected for this workspace.',
            saved: 'ERD workspace saved',
            loaded: 'ERD workspace loaded',
            deleted: 'ERD workspace deleted',
            metadataRefreshed: 'Metadata refreshed',
            metadataRefreshFailed: 'Failed to refresh metadata',
            removeConstraintConfirm: (type: string, constraintName: string) => `Are you sure you want to remove this ${type.toUpperCase()} (${constraintName})?`,
            removeConstraintSuccess: (type: string) => `${type.toUpperCase()} removed successfully`,
            removeConstraintFailed: (type: string) => `Failed to remove ${type.toUpperCase()}`,
            removeRelationshipConfirm: (constraintName: string) => `Are you sure you want to drop the foreign key constraint (${constraintName})?`,
            removeRelationshipSuccess: 'Relationship removed successfully',
            removeRelationshipFailed: 'Failed to remove relationship',
            relationshipCreated: 'Relationship created',
            relationshipCreateFailed: 'Failed to create relationship',
            exportedPng: 'Exported as PNG',
            exportedSql: 'Exported as SQL',
            saveDialogUpdateTitle: 'Update ERD workspace',
            saveDialogCreateTitle: 'Save ERD workspace',
            saveDialogError: 'Failed to save ERD workspace',
            saveDialogName: 'Workspace name',
            saveDialogNamePlaceholder: 'e.g. Payments schema map',
            saveDialogNotes: 'Notes',
            saveDialogNotesPlaceholder: 'Add some context so this layout is easier to revisit later.',
            saveDialogCancel: 'Cancel',
            saveDialogSaving: 'Saving...',
            saveDialogUpdate: 'Update',
            saveDialogSave: 'Save workspace',
        },
        commandPalette: {
            switchedTo: (connectionName: string, database?: string | null) => `Switched to ${connectionName}${database ? ` (${database})` : ''}`,
            searchPlaceholder: 'Search tables, views or run commands...',
            loading: 'AI is thinking...',
            noResults: 'No results found',
            suggestedCommands: 'Suggested Commands',
            syncIndex: 'Sync Index',
            syncComplete: 'Sync complete',
            queryHistory: 'Query History',
            naturalLanguageHint: 'Use natural language for semantic search',
            searchResults: 'Search Results',
            enterToOpen: 'ENTER TO OPEN',
            navigate: 'Navigate',
            open: 'Open',
        },
        adminDashboardPage: {
            adminPanel: 'Admin Panel',
            userManagement: 'User Management',
            auditLogs: 'Audit Logs',
            usersShort: 'Users',
            auditShort: 'Audit',
        },
        queryProject: {
            title: 'Query library',
            description: 'Pin, group, and reopen queries like a lightweight IDE.',
            openLibrary: 'Open library',
            pinned: 'Pinned',
            pinHint: 'Pin queries to keep the important ones nearby.',
            recent: 'Recent',
            noHistory: 'No query runs yet.',
            run: 'Run',
            folders: 'Folders',
            noSavedQueries: 'No saved queries yet.',
            noFolder: 'No folder',
            queryCount: (count: number) => `${count} queries`,
            topTags: 'Top tags',
        },
        savedQueries: {
            title: 'Saved queries',
            description: 'Browse, preview, open, or manage saved queries.',
            searchPlaceholder: 'Search queries...',
            unknownOwner: 'Unknown owner',
            empty: 'No saved queries yet',
            noMatches: 'No matches found',
            firstSaveHint: 'Use Ctrl+S in the Query Editor to save your first query',
            deleted: 'Saved query deleted',
            deleteFailed: 'Failed to delete saved query',
            pin: 'Pin',
            unpin: 'Unpin',
            history: 'History',
            preview: 'Preview',
            open: 'Open',
            selectToPreview: 'Select a query to preview',
            historyTitle: 'Saved query history',
            noVersions: 'No versions yet',
            name: 'Name',
        },
        saveQuery: {
            updateTitle: 'Update saved query',
            createTitle: 'Save query',
            description: 'Save or update a saved query with sharing scope and description.',
            displayName: 'Display name',
            namePlaceholder: 'e.g. Revenue by week',
            visibility: 'Visibility',
            private: 'Private',
            workspaceWide: 'Workspace-wide',
            workspaceTeam: 'Workspace / Team',
            chooseWorkspace: 'Choose workspace',
            folderGroup: 'Folder / Group',
            folderPlaceholder: 'analytics, ops, growth...',
            tags: 'Tags (comma-separated)',
            tagsPlaceholder: 'dashboard, churn, monthly',
            details: 'Description',
            detailsPlaceholder: 'Short context so teammates know what this query is for.',
            cancel: 'Cancel',
            saving: 'Saving...',
            update: 'Update',
            save: 'Save query',
            saveFailed: 'Failed to save query',
        },
        dashboard: {
            defaultWidgetName: 'Query Widget',
            newDashboard: 'New Dashboard',
            saved: 'Widget saved to dashboard',
        },
        dashboardPage: {
            confirmDeleteConnection: 'Are you sure you want to delete this connection?',
            deleteConnectionFallback: 'Failed to delete connection',
            systemActor: 'System',
            backToWelcome: 'Back to Welcome',
            databaseIntelligence: 'Database Intelligence',
            welcomeTitle: 'Welcome to Data Explorer',
            welcomeDescription: 'Manage your databases, execute queries, and visualize data with ease.',
            newQueryTitle: 'New Query',
            newQueryDescription: 'Open a SQL editor to run arbitrary queries.',
            newConnectionTitle: 'New Connection',
            newConnectionDescription: 'Connect to a new PostgreSQL or MySQL database.',
            browseDataTitle: 'Browse Data',
            browseDataDescription: 'Explore tables and schemas in the sidebar.',
            insightsTitle: 'Database Insights',
            insightsDescription: 'View metrics, storage usage, and trends.',
            selectConnectionFirst: 'Select a connection first',
            recentConnections: 'Recent Connections',
            connect: 'Connect',
            shareWithTeam: 'Share with Team',
            noConnections: 'No connections yet. Create one to get started.',
            quickStats: 'Quick Stats',
            activeConnections: 'Active Connections',
            queriesRun: 'Queries Run',
            tablesAccessed: 'Tables Accessed',
            proTipTitle: 'Pro Tip',
            proTipPrefix: 'You can use',
            proTipSuffix: 'to quickly open a new query tab from anywhere in the application.',
            recentDashboards: 'Recent Dashboards',
            widgetCount: (count: number) => `${count} ${count === 1 ? 'widget' : 'widgets'}`,
            noDashboards: 'No dashboards yet. Save your first chart from query results.',
            teamActivity: 'Team Activity',
            noTeamActivity: 'No team activity yet.',
        },
        noSqlDashboard: {
            confirmDeleteConnection: 'Are you sure you want to delete this connection?',
            deleteConnectionFallback: 'Failed to delete connection',
            welcomeTitle: 'Welcome to Data Explorer',
            welcomeDescription: 'Work seamlessly with MongoDB, run MQL queries and handle massive JSON datasets with ease.',
            selectCollectionTitle: 'Select Collection',
            selectCollectionDescription: 'Open left sidebar to select a connection and collection.',
            newConnectionTitle: 'New Connection',
            newConnectionDescription: 'Add a new MongoDB Atlas or Redis cluster for management.',
            browseDocumentsTitle: 'Browse Documents',
            browseDocumentsDescription: 'Explore databases and collections of the current connection.',
            recentConnections: 'Recent NoSQL Connections',
            open: 'Open',
            noConnections: 'No connections yet. Create one to get started.',
        },
        queryToolbar: {
            explain: 'AI Explain',
            runCompact: 'Run',
            runFull: 'Execute',
            aiShort: 'AI',
            aiSql: 'AI SQL',
            sqlSequence: 'SQL Sequence',
            refreshSidebar: 'Refresh Sidebar',
            refresh: 'Refresh',
            format: 'Format',
            clear: 'Clear',
            save: 'Save',
            open: 'Open',
            history: 'History',
            actions: 'Actions',
            formatSql: 'Format SQL',
            saveQuery: 'Save Query',
            openSaved: 'Open Saved',
            clearAll: 'Clear All',
            limit: 'Limit',
            max50k: 'Max 50k',
        },
        visualizePage: {
            hostLabel: 'local',
            goBack: 'Go Back',
            addConnection: 'Add Connection',
            noConnections: {
                sql: {
                    title: 'No SQL Connections',
                    description: 'Add a SQL database connection to start visualizing.',
                },
                nosql: {
                    title: 'No NoSQL Connections',
                    description: 'Add a MongoDB or Redis connection to start visualizing.',
                },
            },
            selectConnection: {
                sql: 'Select SQL Connection',
                nosql: 'Select NoSQL Connection',
                description: 'Choose a database connection to start visualizing.',
            },
            noCollectionTitle: 'No collection selected',
            noCollectionDescription: 'Open a collection in the NoSQL workspace first, then run a query or pipeline to build a result set for this page.',
            backToNoSqlWorkspace: 'Back to NoSQL workspace',
            loadingVisualizationTitle: 'Loading visualization data',
            loadingVisualizationDescription: (collection: string) => `Fetching a document sample from ${collection} to build the first chart.`,
            noResultsTitle: 'No results to visualize yet',
            noResultsErrorDescription: (collection: string, message: string) => `Could not load a sample from ${collection}: ${message}`,
            noResultsEmptyDescription: (collection: string) => `The ${collection} collection does not have chart-ready documents yet. Try another query or check the source data.`,
            retrySampleLoad: 'Retry sample load',
            backToNoSqlEditor: 'Back to NoSQL editor',
            noSqlTitle: 'NoSQL Visualize',
            noSqlDescription: 'A dedicated page for extracting insight from the current result set without crowding the MQL editor.',
            documents: 'documents',
            chartHint: 'If you need collection-wide grouping or more advanced metrics, go back to the Aggregation Builder, run the pipeline, then return here.',
            chartStudio: 'Chart Studio',
        },
        explorerSidebar: {
            syncFailed: 'Sync failed',
            refreshingHierarchy: 'Refreshing hierarchy...',
            refreshed: 'Refreshed',
            syncingIndex: 'Syncing index...',
            indexSynced: 'Index synced!',
            switchedToConnection: (connectionName: string) => `Switched to ${connectionName}`,
            title: 'Explorer',
            localSearchPlaceholder: 'Find entities...',
            globalSearchPlaceholder: 'Global Search...',
            localInstance: 'Local Instance',
            connected: 'Connected',
        },
        connectionSelector: {
            confirmDeleteConnection: 'Are you sure you want to delete this connection?',
            deleteConnectionFallback: 'Error deleting connection',
            selectInstance: 'Select Instance',
            noSqlInstances: 'NoSQL Instances',
            sqlInstances: 'SQL Instances',
            availableInstances: 'Available Instances',
            provisionServer: 'Provision New Server',
            unknownHealth: 'unknown',
            readOnly: 'Read-only',
            check: 'Check',
        },
        noSqlSidebar: {
            searchPlaceholder: 'Find document/collection...',
            onlySupports: 'The NoSQL workspace only supports MongoDB or Redis connections.',
            currentSelection: (type: string) => `Current selection: ${type}`,
            scanningBson: 'Scanning BSON',
            noCollectionsFound: 'No collections found',
            connected: 'NoSQL Connected',
        },
        noSqlMainContent: {
            executionDisabledGuardrail: 'Query execution is disabled for this connection.',
            readOnlyGuardrail: 'Read-only mode is enabled. Only find/aggregate are allowed.',
            performanceGuardrail: 'Results are guarded with execution limits to protect performance.',
            gridTitle: 'Flattened Result Grid',
            gridDescription: 'Scan documents as columns to compare fields and inspect rows faster.',
            insightsTitle: 'Result Set Insights',
            insightsDescription: 'Turn the current result sample into grouped metrics instead of charting raw documents.',
            schemaTitle: 'Schema Analysis',
            schemaDescription: 'Inspect field coverage, type distribution, and sample values for the collection.',
            pipelineOutputTitle: 'Pipeline Output',
            treeTitle: 'Tree Result View',
            treeDescription: 'Preserve BSON/JSON structure so you can inspect the real document shape.',
            docsLabel: 'docs',
            waitingTitle: 'Waiting for a NoSQL connection...',
            waitingDescription: 'You are currently selecting a relational connection. Choose MongoDB or Redis from the sidebar to open the NoSQL Studio.',
            guardrailsTitle: 'NoSQL guardrails',
            closeCollection: 'Close collection',
            aggregationBuilder: 'Aggregation Pipeline Builder',
            visualBuilder: 'Visual MQL Builder',
            formatHint: 'Shift + Alt + F to format',
            askAiMql: 'Ask AI to generate MQL',
            capped: 'Capped',
            hideResultsPanelTitle: 'Hide results panel',
            showResultsPanelTitle: 'Show results panel',
            hideResults: 'Hide results',
            showResults: 'Show results',
            run: 'Run',
            closeResultsPanel: 'Close results panel (Ctrl+J)',
            queryingBson: 'Querying BSON...',
            buildPipelineHint: 'Build a pipeline, then run it to inspect results',
            clickRunHint: 'Click Run to fetch documents',
        },
        queryResults: {
            failed: 'QUERY FAILED',
            empty: 'Run a query to see results',
            dataCompact: 'Data',
            dataFull: 'Data Output',
            messagesCompact: 'Msgs',
            messagesFull: 'Messages',
            planCompact: 'Plan',
            planFull: 'Query Plan',
            timePrefix: 'Time: ',
            clearResults: 'Clear results',
            saveToDashboard: 'Save to dashboard',
            closePanel: 'Close Panel (Ctrl+J)',
            error: 'ERROR:',
            success: 'QUERY EXECUTED SUCCESSFULLY.',
            rowsAffected: 'ROWS AFFECTED:',
            columnsReturned: 'COLUMNS RETURNED:',
            executionTime: 'EXECUTION TIME:',
            completedAt: 'COMPLETED AT:',
            sqlStatement: 'SQL STATEMENT:',
            noMessages: 'No messages to display.',
        },
        queryEditor: {
            explainPrompt: 'Explain this SQL in execution order. Do not generate new SQL. Return markdown with sections for overall summary, step-by-step explanation, and important notes or risks. If this is a multi-statement script, explain each statement in order.',
            readOnlyGuardrail: 'Connection is read-only',
            executionDisabledGuardrail: 'query execution is disabled',
            serverGuardrail: (rows: string) => `server guardrail: max ${rows} rows`,
            requestedLimit: (rows: string | number) => `requested limit: ${rows} rows`,
            timeoutGuardrail: '~30s timeout',
            savedQueryUpdated: 'Saved query updated',
            defaultQueryName: (dateLabel: string) => `Query ${dateLabel}`,
            querySaved: 'Query saved',
            presenceLabel: 'Query live',
            presenceEmpty: 'No one on this query',
            blockedReadOnly: 'Read-only protection active',
            blockedPolicy: 'Execution blocked by connection policy',
            connectionGuardrails: 'Connection guardrails',
        },
        app: {
            routeLoading: 'Loading...',
        },
        navMainActions: {
            insights: 'Insights',
            visualize: 'Visualize',
            diagram: 'Diagram',
        },
        navbar: {
            teams: 'Teams',
        },
        navMenus: {
            file: 'File',
            fileOperations: 'File Operations',
            newQuery: 'New Query',
            duplicateTab: 'Duplicate Tab',
            closeAllTabs: 'Close All Tabs',
            edit: 'Edit',
            undo: 'Undo',
            redo: 'Redo',
            cut: 'Cut',
            copy: 'Copy',
            paste: 'Paste',
            view: 'View',
            hideSidebar: 'Hide Sidebar',
            showSidebar: 'Show Sidebar',
            hideResultPanel: 'Hide Result Panel',
            showResultPanel: 'Show Result Panel',
            toggleFullScreen: 'Toggle Full Screen',
            help: 'Help',
            documentation: 'Documentation',
            checkUpdates: 'Check for Updates...',
            globalShortcuts: 'Global shortcuts: Ctrl+N, Ctrl+I, Ctrl+B, Ctrl+J',
        },
        navUserSection: {
            aiAssistantTitle: 'AI Assistant (Ctrl+I)',
            turnOffDesktopMode: 'Turn off desktop mode',
            turnOnDesktopMode: 'Turn on desktop mode',
            profile: 'Profile',
            billing: 'Billing',
            settings: 'Settings',
            teams: 'Teams',
            adminPanel: 'Admin Panel',
            logOut: 'Log out',
        },
        queryHistory: {
            title: 'Query History',
            entryCount: (count: number) => `${count} ${count === 1 ? 'entry' : 'entries'}`,
            refresh: 'Refresh',
            description: 'Review executed query history, search past entries, and reopen them in the editor.',
            unknownQuery: 'Unknown Query',
            searchPlaceholder: 'Search queries...',
            clearAll: 'Clear All',
            loading: 'Loading history...',
            empty: 'No queries executed yet',
            noMatches: 'No matching queries',
            rowsLabel: 'rows',
            synced: 'Synced',
            databaseFallback: 'Database',
            openInEditor: 'Open in editor',
            copySql: 'Copy SQL',
            timeLocale: 'en-US',
        },
        sqlSequence: {
            title: 'SQL Sequence',
            description: 'Reorder SQL blocks and run them sequentially in the order you choose.',
            reorderHint: 'Drag blocks to reorder, or use the up/down buttons.',
            addStep: 'Add step',
            dragToReorder: 'Drag to reorder',
            step: 'Step',
            moveUp: 'Move up',
            moveDown: 'Move down',
            deleteStep: 'Delete step',
            sqlPlaceholder: 'Enter SQL for this step...',
            nonEmptySteps: (count: number) => `${count} non-empty steps`,
            close: 'Close',
            applyToEditor: 'Apply to editor',
            runSequence: 'Run sequence',
        },
        aiQueryExplanation: {
            title: 'AI Query Explanation',
            description: 'AI breaks down the SQL step by step, explains the intent, and calls out important notes.',
            query: 'Query',
            explanation: 'Explanation',
            loading: 'AI is analyzing this SQL...',
            fallback: 'The AI did not return an explanation yet.',
            close: 'Close',
        },
        noSqlQuery: {
            noActiveConnection: 'No active connection',
            executionDisabled: 'Query execution is disabled for this connection',
            selectCollection: 'Please select a collection first',
            payloadObjectRequired: 'MQL payload must be a JSON object',
            invalidJson: 'Invalid MQL JSON',
            missingActionCollection: 'MQL JSON must contain "action" and "collection" fields',
            readOnlyViolation: 'This connection is read-only. Only find and aggregate are allowed.',
            pipelineResults: 'pipeline results',
            documents: 'documents',
            requestedLimitHint: (limit: string, noun: string) => `Showing the first ${limit} ${noun} requested by this query.`,
            guardrailLimitHint: (limit: string, noun: string) => `Showing the first ${limit} ${noun} because a performance guardrail capped the result set.`,
            resultsLabel: 'results',
            countLabel: 'count',
            insertedLabel: 'inserted',
            updatedLabel: 'updated',
            deletedLabel: 'deleted',
            valuesLabel: 'values',
            docsLabel: 'docs',
            loadedPipeline: (count: number, durationMs: number) => `Loaded ${count} pipeline results (${durationMs}ms)`,
            countedDocuments: (count: number, durationMs: number) => `Counted ${count} documents (${durationMs}ms)`,
            insertedOne: (durationMs: number) => `Inserted 1 document (${durationMs}ms)`,
            insertedMany: (count: number, durationMs: number) => `Inserted ${count} documents (${durationMs}ms)`,
            matchedHint: (count: number) => `${count} documents matched the filter`,
            updatedDocuments: (count: number, durationMs: number) => `Updated ${count} documents (${durationMs}ms)`,
            deletedDocuments: (count: number, durationMs: number) => `Deleted ${count} documents (${durationMs}ms)`,
            loadedDistinct: (count: number, durationMs: number) => `Loaded ${count} distinct values (${durationMs}ms)`,
            loadedDocuments: (count: number, durationMs: number) => `Loaded ${count} documents (${durationMs}ms)`,
            executionFailed: 'MQL Execution Failed',
        },
        jsonTreeView: {
            copyValue: 'Copy value',
            copyObject: 'Copy object',
            itemCount: (count: number) => `${count} ${count === 1 ? 'item' : 'items'}`,
            keyCount: (count: number) => `${count} ${count === 1 ? 'key' : 'keys'}`,
        },
        noSqlVisualize: {
            documentCount: 'Document count',
            sum: 'Sum',
            average: 'Average',
            minimum: 'Minimum',
            maximum: 'Maximum',
            numericFieldFallback: 'numeric field',
            countShort: 'Count',
            bucket: 'Bucket',
            empty: 'No query results to visualize yet.',
            notChartReadyTitle: 'This result set is not chart-ready yet.',
            notChartReadyDescription: 'Use the Aggregation Builder to shape grouped fields first, or switch to Grid to inspect the raw result set.',
            currentSample: 'Current sample',
            documentsFrom: (collection: string) => `documents from ${collection}`,
            groupingFields: 'Grouping fields',
            bestDefault: (field: string) => `Best default: ${field}`,
            noStrongGrouping: 'No strong grouping field yet.',
            numericMetrics: 'Numeric metrics',
            usingDocumentCount: 'Currently using document count.',
            topBucket: 'Top bucket',
            noTopBucket: 'No dominant bucket yet.',
            groupBy: 'Group by',
            groupFieldPlaceholder: 'Choose a grouping field',
            metric: 'Metric',
            metricPlaceholder: 'Choose a metric',
            countMetric: 'Document count',
            numericField: 'Numeric field',
            notNeededForCount: 'Not needed for Count',
            numericFieldPlaceholder: 'Choose a numeric field',
            insightHint: 'Visualize now focuses on quick insight extraction from the current result set. For collection-wide metrics or more advanced grouping, shape the dataset with the Aggregation Builder first and then return here.',
            compareBy: (field: string) => `Comparing groups by ${field}`,
            insufficientNumericData: 'Not enough numeric data for the current metric. Switch to Count or choose another numeric field.',
            collectionFallback: 'collection',
            currentCollectionFallback: 'the current collection',
        },
        aiMessageBubble: {
            confirmDelete: 'Delete this message?',
            cancelEdit: 'Cancel',
            saveAndSend: 'Save & Send',
            insertToEditor: 'Insert into editor',
            runNow: 'Run now',
            copySql: 'Copy SQL',
            copyMql: 'Copy MQL',
            suggestedChart: 'Suggested chart',
            insertSuggestion: 'Insert suggestion',
            runSuggestion: 'Run suggestion',
            copySuggestion: 'Copy suggestion',
            editMessage: 'Edit message',
            copyMessage: 'Copy message',
        },
        forgotPassword: {
            otpSent: 'OTP sent to your email!',
            resetSuccess: 'Password reset successfully!',
            sendOtpError: 'Error sending OTP',
            invalidOtp: 'Invalid OTP',
            forgotTitle: 'Forgot Password',
            resetTitle: 'Reset Password',
            forgotDescription: 'Enter your email to receive an OTP',
            resetDescription: 'Enter the 6-digit OTP sent to your email',
            sendOtp: 'Send OTP',
            otpLabel: 'OTP Code',
            newPasswordLabel: 'New Password',
            resetPassword: 'Reset Password',
            backToLogin: 'Back to login',
        },
        landingPage: {
            seoTitle: 'Data Explorer - Smart Database IDE',
            seoDescription: 'Explore and manage SQL & NoSQL with the power of AI. Modern, fast, and secure database explorer.',
        },
        landingHeader: {
            backToTopAria: 'Back to top',
            features: 'Features',
            liveDemo: 'Live Demo',
            pricing: 'Pricing',
            docs: 'Docs',
            changelog: 'Changelog',
            goBack: 'Go Back',
            logout: 'Logout',
            workspace: 'Workspace',
            login: 'Login',
            startAnalysis: 'Start Analysis',
            toggleMenuAria: 'Toggle menu',
        },
        landingFooter: {
            product: 'Product',
            resources: 'Resources',
            legal: 'Legal',
            productLinks: ['Features', 'Gemini 3.1', 'Visual ERD', 'Changelog'],
            resourceLinks: ['Documentation', 'Clean Code Guide', 'Vitest Suite', 'Status'],
            legalLinks: ['Privacy', 'Terms', 'AES Security', 'Compliance'],
            brandDescription: 'Precision engineered data tools for the next generation of engineers. Built with speed and security at its core.',
            builtForTeams: 'BUILT FOR MODERN DATA TEAMS.',
            liveStatus: 'Live Status: Nominal',
            languageLabel: 'English (US)',
        },
        workflowSection: {
            title: 'Intelligent Workflow',
            description: 'The perfect synergy between human intuition and artificial intelligence.',
            steps: [
                { title: 'Discovery', description: 'Auto-scans and indexes your entire data schema instantly.' },
                { title: 'AI Augmentation', description: 'Gemini 3.1 analyzes context and optimizes your SQL constructs.' },
                { title: 'Instant Execution', description: 'Real-time execution with beautifully visualized results.' },
                { title: 'Sync & Save', description: 'AES-256 encrypted storage and secure multi-device sync.' },
            ],
        },
        featuresSection: {
            title: 'Unified Intelligence',
            description: 'Not just an editor. A command center for your data, built with modern craftsmanship.',
            features: [
                {
                    title: 'Monaco Editor',
                    description: 'Professional grade editor with precise Auto-complete, AI-driven schema suggestions, and Intellisense.',
                },
                {
                    title: 'Universal SQL & NoSQL Power',
                    description: 'Unified experience across SQL & NoSQL. Share same shortcuts, menus, and Visualize designers between relational and document databases.',
                },
                {
                    title: 'Live ERD Visualizer',
                    description: 'Automatically generate and explore interactive Entity Relationship Diagrams (ERD) powered by React Flow.',
                },
                {
                    title: 'Gemini 3.1 AI Agent',
                    description: 'Context-aware AI understands your schema, converts natural language to SQL, and highlights query bugs.',
                },
                {
                    title: 'Enterprise Security',
                    description: 'Multi-layer security: Reinforced SQL Guard, SSRF tunnel protection, strict team privacy, and AES-256-GCM encryption.',
                },
                {
                    title: 'History & Data Export',
                    description: 'Track query timings, retain execution history, and instantly export data grids to CSV, JSON, or SQL format.',
                },
            ],
        },
        heroSection: {
            titlePrefix: 'THE AI-POWERED',
            titleHighlight: 'DATABASE IDE',
            description: 'Ditch the legacy tools. Connect to SQL & NoSQL simultaneously, secure your workflows with enterprise-grade guardrails, and write queries at lightspeed.',
            openWorkspace: 'Open Workspace',
            claimAccess: 'Claim Your Access',
            documentation: 'Documentation',
        },
        aiSpotlight: {
            titleLine1: 'The Ultimate',
            titleLine2: 'AI Data Assistant.',
            description: 'Automatically parses your data schema. Use natural language to perform complex queries. With multimodal vision, the AI can even read ERD image diagrams and reconstruct DB structures.',
            talkToAssistant: 'Talk to Assistant',
            learnHowItWorks: 'Learn how it works',
        },
        docsCta: {
            title: 'Ready to dive deeper?',
            description: 'Our comprehensive documentation covers everything from initial setup to advanced AI prompt engineering.',
            apiReference: 'API Reference',
            architecture: 'Architecture',
            openDocumentation: 'Open Documentation',
        },
        pricingSection: {
            title: 'Clear pricing for a database workspace',
            description: 'Pay in VND through MoMo and ZaloPay. USD prices are reference copy only.',
            bestValue: 'Best value',
            openWorkspace: 'Open workspace',
            upgradeInProfile: 'Upgrade in profile',
            footerNote: 'MoMo and ZaloPay checkout activates Pro only after a confirmed provider webhook.',
        },
        documentationPage: {
            defaultTitle: 'Docs',
            seoTitle: (itemTitle: string) => `${itemTitle}`,
            seoDescription: (itemTitle: string) => `In-depth guide for ${itemTitle} in Data Explorer. Learn how to optimize your data workflow.`,
            docsLabel: 'Docs',
            quickSearch: 'Quick search docs...',
            goBack: 'Go Back',
            launchApp: 'Launch App',
            editPage: 'Edit this page',
            releaseDate: 'June 2026',
            helpful: 'Was this helpful?',
            readyTitle: 'Ready to explore data?',
            readyDescription: 'Join the community on GitHub to contribute to the smartest local database IDE.',
            tableOfContents: 'Table of Contents',
            noHeadings: 'No headings found',
        },
        usersView: {
            loadFailed: 'Failed to load users',
            roleUpdated: (role: string) => `Role updated to ${role}`,
            passwordPrompt: 'Enter new password (min 6 characters):',
            passwordTooShort: 'Password must be at least 6 characters',
            passwordResetSuccess: 'Password reset successfully',
            deleteConfirm: (email: string) => `Are you sure you want to delete user ${email}?`,
            userDeleted: 'User deleted successfully',
            loading: 'Loading...',
            demoteTitle: 'Demote to User',
            promoteTitle: 'Promote to Admin',
            demote: 'Demote',
            promote: 'Promote',
            unbanTitle: 'Unban User',
            banTitle: 'Ban User',
            unban: 'Unban',
            ban: 'Ban',
            resetPassword: 'Reset Password',
            reset: 'Reset',
            deleteUser: 'Delete User',
            delete: 'Delete',
            noName: 'No name',
            banned: 'Banned',
            role: 'Role',
            admin: 'Admin',
            user: 'User',
            joined: 'Joined',
            name: 'Name',
            joinedDate: 'Joined Date',
            actions: 'Actions',
            noUsers: 'No users found.',
        },
        auditLogsView: {
            security: 'Security',
            data: 'Data',
            team: 'Team',
            user: 'User',
            system: 'System',
            other: 'Other',
            loading: 'Loading audit logs...',
            searchPlaceholder: 'Search actions or users...',
            all: 'All',
            noMatches: 'No matching audit logs found.',
            userLabel: 'User',
            systemActor: 'System',
            ipAndTime: 'IP and time',
            action: 'Action',
            ipAndDevice: 'IP & Device',
            time: 'Time',
            detailsTitle: 'Audit Log Details',
            location: 'Location',
            extendedData: 'Extended Data',
            noExtendedData: 'No extended data available',
            unknown: 'unknown',
        },
        shareConnectionDialog: {
            sharedSuccess: 'Connection shared with team!',
            shareFailed: 'Error sharing connection',
            createTeamPrompt: 'Enter new team name:',
            createTeamFailed: 'Error creating team',
            title: 'Share Connection with Team',
            description: 'Pick a team and teamspace to place this connection in the shared workspace.',
            selectTeam: 'Select Team',
            selectTeamPlaceholder: 'Select a team...',
            noTeams: 'You are not in any teams yet',
            selectTeamspace: 'Select Teamspace',
            optional: 'Optional...',
            unassigned: 'Unassigned',
            createNewTeam: 'Create new team',
            cancel: 'Cancel',
            shareNow: 'Share Now',
        },
        bulkImportDialog: {
            csvOnly: 'Please select a CSV file',
            invalidCsv: 'CSV file is empty or invalid',
            importSuccess: (count: number) => `Imported ${count} rows successfully!`,
            importFailed: 'Import failed',
            fallbackImportError: 'Import failed',
            title: 'Bulk Import Data',
            dropHere: 'Drop file here',
            dragHere: 'Drag & drop CSV file here',
            browseHint: 'Or click to browse files',
            selectFile: 'Select File',
            rowsReady: (count: number) => `${count} rows ready for import`,
            changeFile: 'Change file',
            readOnlyBlocked: 'This connection is read-only, so import is blocked.',
            disabledBlocked: 'Import/export has been disabled for this connection.',
            cancel: 'Cancel',
            startImport: 'Start Import',
        },
        foreignKeyDialog: {
            title: 'Create Foreign Key Relationship',
            description: (sourceTable: string, targetTable: string) => `Define the relationship between ${sourceTable} and ${targetTable}.`,
            constraintName: 'Constraint Name',
            childTable: 'Foreign Key Table (Child)',
            parentTable: 'Primary Key Table (Parent)',
            table: 'Table',
            column: 'Column',
            refs: 'Refs',
            onDelete: 'On Delete',
            onUpdate: 'On Update',
            warning: 'Creating this relationship will modify your database schema. Ensure that existing data does not violate this new constraint, or the operation will fail.',
            cancel: 'Cancel',
            createRelationship: 'Create Relationship',
        },
        relativeTime: {
            locale: 'en',
        },
    },
} as const;

export function getWorkspaceText(lang: AppLang | string | null | undefined) {
    return workspaceText[normalizeAppLang(lang)];
}

export function formatWorkspaceRelativeTime(lang: AppLang | string | null | undefined, timestamp: number) {
    const diffMinutes = Math.round((timestamp - Date.now()) / 60000);
    const absMinutes = Math.abs(diffMinutes);
    const rtf = new Intl.RelativeTimeFormat(getWorkspaceText(lang).relativeTime.locale, { numeric: 'auto' });

    if (absMinutes < 60) {
        return rtf.format(diffMinutes, 'minute');
    }

    const diffHours = Math.round(diffMinutes / 60);
    if (Math.abs(diffHours) < 24) {
        return rtf.format(diffHours, 'hour');
    }

    return rtf.format(Math.round(diffHours / 24), 'day');
}
