export const AI_CONSTANTS = {
  // Timeouts (ms)
  DEFAULT_PROVIDER_TIMEOUT_MS: 15_000,
  DEFAULT_STREAM_IDLE_TIMEOUT_MS: 15_000,

  // Token limits
  MAX_OUTPUT_TOKENS: 8192,
  COMPLETION_MAX_OUTPUT_TOKENS: 32,
  AUTOCOMPLETE_MAX_OUTPUT_TOKENS: 32,
  AUTOCOMPLETE_NLP_MAX_OUTPUT_TOKENS: 1000,

  // Temperatures
  TEMPERATURE_CREATIVE: 0.7,
  TEMPERATURE_PRECISE: 0.1,

  // Routing thresholds
  PROMPT_LENGTH_FAST: 1200,
  CONTEXT_LENGTH_MEDIUM: 2500,
  SCHEMA_CONTEXT_LENGTH_LARGE: 6000,

  // Complexity scoring
  COMPLEXITY_IMAGE_WEIGHT: 6,
  COMPLEXITY_CURRENT_INFO_WEIGHT: 4,
  COMPLEXITY_DEEP_REASONING_WEIGHT: 3,
  COMPLEXITY_COMPLEX_DATA_WEIGHT: 2,
  COMPLEXITY_LONG_PROMPT_WEIGHT: 2,
  COMPLEXITY_LARGE_CONTEXT_WEIGHT: 2,
  COMPLEXITY_LARGE_SCHEMA_WEIGHT: 1,
  COMPLEXITY_PLANNING_MODE_WEIGHT: 1,
  COMPLEXITY_GEMINI_THRESHOLD: 5,

  // Cache TTL (ms)
  AUTOCOMPLETE_CACHE_TTL_MS: 3_600_000, // 1 hour
  SCHEMA_CACHE_TTL_MS: 900_000, // 15 minutes

  // Cursor limits
  AUTOCOMPLETE_CURSOR_MAX_LENGTH: 1500,
} as const;
