import { useCallback } from 'react';
import { toast } from 'sonner';

interface UseErdExportOptions {
    selectedDatabase?: string;
    tableData: Record<string, { columns: Array<{ name: string; type: string; isPrimaryKey?: boolean; nullable?: boolean }> }>;
    visibleTableNames: Set<string>;
    lang: string;
}

export function useErdExport({
    selectedDatabase,
    tableData,
    visibleTableNames,
    lang,
}: UseErdExportOptions) {
    const handleExportPNG = useCallback(() => {
        import('html-to-image').then(({ toPng }) => {
            const canvas = document.querySelector('.react-flow') as HTMLElement | null;
            if (!canvas) return;

            toPng(canvas, { backgroundColor: '#0a0a0b', quality: 1, pixelRatio: 2 }).then((dataUrl) => {
                const link = document.createElement('a');
                link.download = `erd-${selectedDatabase || 'diagram'}-${Date.now()}.png`;
                link.href = dataUrl;
                link.click();
                toast.success(lang === 'vi' ? 'Đã xuất PNG' : 'Exported as PNG');
            });
        });
    }, [lang, selectedDatabase]);

    const handleExportSQL = useCallback(() => {
        if (!tableData || visibleTableNames.size === 0) return;

        let sql = '-- Generated by Data Explorer ERD\n\n';
        Array.from(visibleTableNames).forEach((tableName) => {
            const metadata = tableData[tableName];
            if (!metadata) return;

            sql += `CREATE TABLE "${tableName}" (\n`;
            sql += metadata.columns
                .map((column) => `    "${column.name}" ${column.type}${column.isPrimaryKey ? ' PRIMARY KEY' : ''}${column.nullable === false ? ' NOT NULL' : ''}`)
                .join(',\n');
            sql += '\n);\n\n';
        });

        const blob = new Blob([sql], { type: 'text/sql' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.download = `erd-${selectedDatabase || 'schema'}-${Date.now()}.sql`;
        link.href = url;
        link.click();
        toast.success(lang === 'vi' ? 'Đã xuất SQL' : 'Exported as SQL');
    }, [lang, selectedDatabase, tableData, visibleTableNames]);

    return {
        handleExportPNG,
        handleExportSQL,
    };
}
